//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define IDCANCEL2                       3
#define ID_SAVE_PROP                    3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MapEditorTYPE               129
#define IDR_RegionTYPE                  130
#define IDR_MENU_POP                    133
#define IDD_DLG_MAP_INFO                134
#define IDD_SELECT_GROUND               135
#define IDD_DLG_SELECT_OBJ              136
#define IDD_SMALL_MAP                   138
#define IDD_OBJ_LIST                    139
#define IDD_DLG_VIEW_PROP               140
#define IDR_TOOLBAR_EDIT_LAYER          141
#define IDD_DLG_LAYER_LIST              142
#define IDD_OBJ_RESOURCE                143
#define IDD_DLG_TRANSOBJ_LIST           144
#define IDD_DLG_TRANSOBJ_EDITER         145
#define IDD_DLG_TIME_EFFECT_EDITOR      147
#define IDD_PROPERITES_DIALOG           148
#define IDD_DLG_TRIGGER_LIST            149
#define IDD_DLG_TRIGGER_EDIT            150
#define IDD_DLG_SELECT_WATER            151
#define IDD_DLG_WATER_AREA_INFO         152
#define IDD_DLG_PERFORMANCE             153
#define IDD_DLG_BACKGROUND_INFO         154
#define IDD_DLG_BACKGROUND              155
#define IDD_DLG_MASK_EDITOR             156
#define IDC_SLIDER_COEF_R               1001
#define IDC_SLIDER_COEF_G               1002
#define IDC_SLIDER_COEF_B               1003
#define IDC_SLIDER_LIGHT_NESS           1004
#define IDC_EDIT_WIDTH                  1005
#define IDC_EDIT_HEIGHT                 1006
#define IDC_COMBO_GRANDTYPE             1007
#define IDC_TAB1                        1008
#define IDC_TREE1                       1009
#define IDC_TREE2                       1010
#define IDC_TREE3                       1011
#define IDC_PICTURE                     1012
#define IDC_GROUND_TYPE_STATIC          1013
#define IDC_STATIC_DIRECT               1014
#define IDC_RADIO1                      1015
#define IDC_RADIO2                      1016
#define IDC_RADIO3                      1017
#define IDC_RADIO4                      1018
#define IDC_RADIO5                      1019
#define IDC_RADIO6                      1020
#define IDC_RADIO7                      1021
#define IDC_RADIO8                      1022
#define IDC_RADIO9                      1023
#define IDC_EDIT_X                      1024
#define IDC_EDIT_Y                      1025
#define IDC_OBJS_LIST_BOX               1026
#define IDC_SELECT_GRID_COLOR           1027
#define IDC_SELECT_BASE_COLOR           1028
#define IDC_LIST1                       1029
#define IDC_LIST2                       1030
#define IDC_SELECT_BACKGROUND_COLOR     1031
#define IDC_BUTTON_NEW_LAYER            1032
#define IDC_BUTTON_DEL_LAYER            1033
#define IDC_BRUSH_SIZE                  1034
#define IDC_BUTTON_COUNT_REF            1035
#define IDC_BUTTON_CLEAN                1036
#define IDC_ELE_RES_LIST                1037
#define IDC_REFRESH                     1038
#define IDC_MAGNET_RADIUS               1039
#define IDC_EDIT1                       1040
#define IDC_EDIT2                       1041
#define IDC_EDIT3                       1042
#define IDC_EDIT4                       1043
#define IDC_EDIT5                       1044
#define IDC_BUTTON1                     1045
#define IDC_BUTTON2                     1046
#define IDC_BUTTON3                     1047
#define IDC_SLIDER1                     1048
#define IDC_PLAY_QUICKLY                1049
#define IDC_SAVE_FRAME                  1050
#define IDC_ADD_REMOVE_FRAME            1051
#define IDC_PLAY                        1052
#define IDC_STOP                        1053
#define IDC_PICTURECTRL_CONTRASTCURVE   1054
#define IDC_EDIT_COEF_R                 1055
#define IDC_EDIT_COEF_G                 1056
#define IDC_EDIT_COEF_B                 1057
#define IDC_EDIT_LIGHT_NESS             1058
#define IDC_COLOR                       1059
#define IDC_EDIT_VERTEX_COLOR           1059
#define IDC_UP                          1060
#define IDC_DOWN                        1061
#define IDC_LEFT                        1062
#define IDC_RIGHT                       1063
#define IDC_EDIT_COLOR_WIDTH            1064
#define IDC_EDIT_COLOR_HEIGHT           1065
#define IDC_BUTTON_BROWSE               1066
#define IDC_EDIT_EFFECT_NAME            1067
#define IDC_EDIT_TOP                    1068
#define IDC_EDIT_LEFT                   1069
#define IDC_EDIT_BOTTOM                 1070
#define IDC_EDIT_RIGHT                  1071
#define IDC_CTRL_SPRITE                 1072
#define IDC_CTRL_TIME                   1073
#define IDC_FREQUENCY                   1074
#define IDC_BEGIN_TIME                  1075
#define IDC_END_TIME                    1076
#define IDC_DELTA                       1077
#define IDC_MAX_DELTA                   1078
#define IDC_COMBO_LAYER                 1079
#define IDC_COMBO_VIEWPORT              1080
#define IDC_CTRL_SPRITE2                1080
#define IDC_CTRL_SINGLE                 1080
#define IDC_BRUSH_SIZE_TEXT             1081
#define IDC_VIEWPORT_SIZE               1082
#define IDC_VIEWPORT_LAYER              1083
#define IDC_MAP_SIZE                    1084
#define IDC_MAP_LAYER                   1085
#define IDC_TAB_GROUND_SIZE             1086
#define IDC_TREE4                       1087
#define IDC_TREE5                       1088
#define IDC_TREE6                       1089
#define IDC_TAB2                        1090
#define IDC_CHECK1                      1091
#define IDC_CHECK2                      1092
#define IDC_CHECK3                      1093
#define IDC_CHECK4                      1094
#define IDC_TRANS_TEXT                  1095
#define IDC_NAME                        1096
#define IDC_POS_X                       1097
#define IDC_POS_Y                       1098
#define IDC_X_REL_SPEED                 1099
#define IDC_Y_REL_SPEED                 1100
#define IDC_GIRD_WIDTH                  1101
#define IDC_GIRD_HEIGHT                 1102
#define IDC_WIDTH                       1103
#define IDC_HEIGHT                      1104
#define IDC_WRAP_HORZ                   1105
#define IDC_WRAP_VERT                   1106
#define IDC_ACTIVE_TOP                  1107
#define IDC_ACTIVE_BOTTOM               1108
#define IDC_ACTIVE_LEFT                 1109
#define IDC_ACTIVE_RIGHT                1110
#define IDC_RESET                       1111
#define IDC_BUTTON_ADD                  1112
#define IDC_BUTTON_EDIT                 1113
#define IDC_BUTTON_DEL                  1114
#define IDC_COMBO1                      1115
#define IDC_CHECK_UNDERGROUND_PALACE    1116
#define ID_LAYER_GROUND                 32790
#define ID_LAYER_WATER_1                32791
#define ID_LAYER_WATER_2                32792
#define ID_LAYER_LOW_1                  32793
#define ID_LAYER_LOW_2                  32794
#define ID_LAYER_LOW_3                  32795
#define ID_LAYER_LOW_4                  32796
#define ID_LAYER_LOW_5                  32797
#define ID_LAYER_LOW_6                  32798
#define ID_LAYER_MIDDLE                 32799
#define ID_LAYER_HIGH_1                 32800
#define ID_LAYER_HIGH_2                 32801
#define ID_LAYER_TRANS                  32802
#define ID_LAYER_TRIGGER                32803
#define ID_LAYER_WATER                  32804
#define ID_LAYER_BACKGROUND             32805
#define ID_LAYER_GAMING                 32806
#define ID_SHOW_GIRD_CLOSE              32807
#define ID_SHOW_GIRD                    32808
#define ID_SHOW_MID_TILE_GIRD           32809
#define ID_SHOW_BIG_TILE_GIRD           32810
#define ID_SHOW_WATER_GIRD              32811
#define ID_SHOW_800X600_GIRD            32812
#define ID_SHOW_1024X768_GIRD           32813
#define ID_SHOW_BLOCK_GIRD              32814
#define ID_SHOW_CITY_GIRD               32815
#define ID_SHOW_LAYER_GROUND            32816
#define ID_SHOW_LAYER_WATER_1           32817
#define ID_SHOW_LAYER_WATER_2           32818
#define ID_SHOW_LAYER_LOW_1             32819
#define ID_SHOW_LAYER_LOW_2             32820
#define ID_SHOW_LAYER_LOW_3             32821
#define ID_SHOW_LAYER_LOW_4             32822
#define ID_SHOW_LAYER_LOW_5             32823
#define ID_SHOW_LAYER_LOW_6             32824
#define ID_SHOW_LAYER_MIDDLE            32825
#define ID_SHOW_LAYER_HIGH_1            32826
#define ID_SHOW_LAYER_HIGH_2            32827
#define ID_SHOW_LAYER_TRANS             32828
#define ID_SHOW_LAYER_TRIGGER           32829
#define ID_SHOW_LAYER_WATER             32830
#define ID_SHOW_SELECT_DLG              32831
#define ID_SHOW_SMALL_MAP               32832
#define ID_SHOW_ELEMENT_LIST            32833
#define ID_VIEW_PROPERT                 32834
#define ID_FILE_SAVE_AS_JPG             32835
#define ID_Menu                         32836
#define ID_IMPORT                       32837
#define ID_EXPORT                       32838
#define ID_EXPORT_TO_RMP                32839
#define ID_POP_ZOOM_IN                  32840
#define ID_POP_ZOOM_OUT                 32841
#define ID_POP_NONZOOM                  32842
#define ID_POP_FULL_SCREEN              32843
#define ID_EXPORT_SMALL_MAP             32844
#define ID_ZOOM_IN                      32845
#define ID_NO_ZOOM                      32846
#define ID_ZOOM_OUT                     32847
#define ID_SHOW_OBJ_RES                 32848
#define ID_MERGE_IMPORT                 32849
#define ID_FILE_EXPORT_JPG              32850
#define ID_Edit_MapInfo                 32851
#define ID_SHOW_BASE                    32852
#define ID_TIME_EFFECT                  32853
#define ID_ITEM_PROP                    32854
#define ID_EDIT_RESET_ALL_OBJS          32855
#define ID_SHOW_EFFECT                  32856
#define ID_TEST_LAYER_BLOCK             32857
#define ID_SHOW_PREDLG                  32858
#define ID_SHOW_ALL_OBJ_RES             32859
#define ID_UPDATE_LKO_EVERY_FRAME       32860
#define ID_VIEW_REPLACE_LKO             32861
#define ID_MASK_EDIT                    32862

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
