
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 此头文件包含当前名字空间下的所有协议。要注意，如果把实现写在头文件里面，
// 包含这个头文件很容易产生循环。

#include "gnet/AddictionControl.hpp"
#include "gnet/AnnounceForbidInfo.hpp"
#include "gnet/Challenge.hpp"
#include "gnet/CouponExchangeRep.hpp"
#include "gnet/CouponExchangeReq.hpp"
#include "gnet/DataBetweenAuAnyAndClient.hpp"
#include "gnet/ErrorInfo.hpp"
#include "gnet/GetUserCouponRep.hpp"
#include "gnet/GetUserCouponReq.hpp"
#include "gnet/InstantAddCashRep.hpp"
#include "gnet/InstantAddCashReq.hpp"
#include "gnet/KeepAlive.hpp"
#include "gnet/KeyExchange.hpp"
#include "gnet/OnlineAnnounce.hpp"
#include "gnet/PortForward.hpp"
#include "gnet/Response.hpp"
#include "gnet/SSOGetTicketRep.hpp"
#include "gnet/SSOGetTicketReq.hpp"
