$axure.loadCurrentPage({
  "url":"人物属性.html",
  "generationDate":new Date(1429602387146.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"54c711b3268e42ea8546b6835395a492",
    "type":"Axure:Page",
    "name":"人物属性",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9815771affcd45c084af8b820fe57b19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5fdd4d782e4bea90f0d8f8f8fd5abb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"03fa4940cc40481ea08506dc57b54f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdceaa01cf0b4020b8fec703e3a9a157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"73e00458693f462a966a87a43e01f3e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c86178ecb1d8461b9d38d34cd8a769c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"b6e1162e1bc84c4c958e9e0ea58f211a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f33b72d435744aedb0305aa58bf2d5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"fbdb51d87bae476e8b2f6abd252c2f85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b6f9f3daaa4693a3324fc211b22f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"a0e5293c8e1e47678fdf4496a18e02a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66350334de374fd58d5c8219333ba708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u10.png"}},
{
          "id":"6c37beee852d4fcbb4e616e87e924e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81cc791c3b3e4b3eaad3e7c4eb6c5e94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"9be2b496971b4f628bd28ba1c75fc550",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e984e3dc044b908bf95b360169bb78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"e478700448384baabeb8f6f09447f825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":280},
            "size":{
              "width":216,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac77f713f673436ab6501c1cf2a93cbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":280},
                "size":{
                  "width":216,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"90711dd229b744929a433b73dce49e74",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":240},
            "size":{
              "width":109,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"0cfda260572840ff897e2e8cff277acc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":240},
            "size":{
              "width":105,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"a5c8de580b9c4edb8f6c8b2b7110e9cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d4c0b1e2274baf88d1745a0a243791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"2e616e2cb3d145d7a9ac966be5cfbf59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6f0bbed646448f9e72559cdce79dfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"213d6635c71746979837f77bdc10c188",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2aa3e08373e49deb166b98435b05974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"3a1c8a04528643de8a32d91037945caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7d820e05bf488faa1b10f9b424c55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":250},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"1089e5eb62c84d5680cf8e1c404e4bfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1acb8aed7ebf40d7af88161d0e9e11be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"1d5243ef90bf469590e7e8034cb110f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e50660b03ef45ae93203579c20fd9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"ba51f27205a246f2a137e92c69ceac7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c534b5e15ded4dddb6c7b716666b0508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"0a78bcc336ba4223a8bbff882473e76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9a7158499348d6aeca628002d0287f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"55d8cdb1c1704afc9b9870b6e2b84186",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":558},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b770f416bc83464a97e6e956887ee9bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":558},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"600e8aaa93dc47c2881004e1266b82c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2162e2b8b1b54a418cc8b34a58a64905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"94674d0d2485448b85ff7c021c2ae1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078229d16f14480dae09274ab14a2e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"1c300b4e05404371863212e8a1698afe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4405aee5e6a43ebb21370977c700e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"04307f70397340c1942ccd9011cd6a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":136},
            "size":{
              "width":115,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7ab0b78fa2b42b7b30a5ee944389c12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":136},
                "size":{
                  "width":115,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u44.png"}},
{
          "id":"c37ec7c4e54d42679b6919b39abc1a55",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c3fda329fb5847179dc42fce3b2d9e1f",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":570},
            "size":{
              "width":328,
              "height":168}},
          "adaptiveStyles":{
}},
{
          "id":"3da9ae1b501d47eaac60e4c992ffb72b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e651148b55b843a7b2fa7bf91e646a4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"54049e757f444fe7a194ac68a08c47a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f340fda0584d47f1a9022f8358836065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"d5ac63f5d33640d1a9fb7ad25ca35594",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"928be671ef87460c8ad73383cd7dd636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"dce6490910df485d8a510fdb6584b8e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0aa6fa8de514fe8826dcb8571402467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"7fd782c715d44904b397fdd792c3c894",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebec7cbc4dab4ee9b8f492a48bdf0038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"b375415126284aebbb349459679bfc73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":171},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"053b5e7f420849f3ad9223f37aefa16e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":171},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"24c6812ab6a94b838227cb02cb6b6bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":111},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cc51ddfa8843ceb7614afb08f73966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":111},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"37286d220fdd4ab9b59100e748091b95",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":280},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"335e4740547b4063aacaa257366fc6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":280},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"e6bd1080ee954b528ea8fe161a5981a8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":320},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3dbeb6ee75346f6806f481516d3d2aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":320},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"d5d21d319fe642ccb89ca254820af7ca",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":360},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d19c325a474a40a365f7d5b6508a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":360},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"696ca86ed8934a578a155458074401f5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":400},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d3c23a580c40c9acb48bc548a7030c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":400},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"d2a104ef14864e4bb20bdc31a982bc96",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":440},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235282bc3cb14f349c33822719b2cfc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":440},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"412441fb2d674dc28994691d2ad2e476",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":235},
            "size":{
              "width":742,
              "height":435}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d720612ecad4609a9f3d69687a47fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":235},
                "size":{
                  "width":742,
                  "height":435}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人物属性/u72.png"}},
{
          "id":"560dd90310464e43885d1b192d9b9d40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":950,
              "y":239},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f23af05854048bb989838560d591cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":950,
                  "y":239},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eff99bb8ebac40db93c9047feffd8097",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":1156,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5824b93622994e9490b311aa3cf28b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":1156,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9815771affcd45c084af8b820fe57b19":{
      "scriptId":"u0"},
    "fe5fdd4d782e4bea90f0d8f8f8fd5abb":{
      "scriptId":"u1"},
    "03fa4940cc40481ea08506dc57b54f45":{
      "scriptId":"u2"},
    "bdceaa01cf0b4020b8fec703e3a9a157":{
      "scriptId":"u3"},
    "73e00458693f462a966a87a43e01f3e7":{
      "scriptId":"u4"},
    "c86178ecb1d8461b9d38d34cd8a769c1":{
      "scriptId":"u5"},
    "b6e1162e1bc84c4c958e9e0ea58f211a":{
      "scriptId":"u6"},
    "f33b72d435744aedb0305aa58bf2d5e1":{
      "scriptId":"u7"},
    "fbdb51d87bae476e8b2f6abd252c2f85":{
      "scriptId":"u8"},
    "d1b6f9f3daaa4693a3324fc211b22f53":{
      "scriptId":"u9"},
    "a0e5293c8e1e47678fdf4496a18e02a3":{
      "scriptId":"u10"},
    "66350334de374fd58d5c8219333ba708":{
      "scriptId":"u11"},
    "6c37beee852d4fcbb4e616e87e924e69":{
      "scriptId":"u12"},
    "81cc791c3b3e4b3eaad3e7c4eb6c5e94":{
      "scriptId":"u13"},
    "9be2b496971b4f628bd28ba1c75fc550":{
      "scriptId":"u14"},
    "75e984e3dc044b908bf95b360169bb78":{
      "scriptId":"u15"},
    "e478700448384baabeb8f6f09447f825":{
      "scriptId":"u16"},
    "ac77f713f673436ab6501c1cf2a93cbe":{
      "scriptId":"u17"},
    "90711dd229b744929a433b73dce49e74":{
      "scriptId":"u18"},
    "0cfda260572840ff897e2e8cff277acc":{
      "scriptId":"u19"},
    "a5c8de580b9c4edb8f6c8b2b7110e9cc":{
      "scriptId":"u20"},
    "c9d4c0b1e2274baf88d1745a0a243791":{
      "scriptId":"u21"},
    "2e616e2cb3d145d7a9ac966be5cfbf59":{
      "scriptId":"u22"},
    "ab6f0bbed646448f9e72559cdce79dfc":{
      "scriptId":"u23"},
    "213d6635c71746979837f77bdc10c188":{
      "scriptId":"u24"},
    "e2aa3e08373e49deb166b98435b05974":{
      "scriptId":"u25"},
    "3a1c8a04528643de8a32d91037945caf":{
      "scriptId":"u26"},
    "7b7d820e05bf488faa1b10f9b424c55e":{
      "scriptId":"u27"},
    "1089e5eb62c84d5680cf8e1c404e4bfa":{
      "scriptId":"u28"},
    "1acb8aed7ebf40d7af88161d0e9e11be":{
      "scriptId":"u29"},
    "1d5243ef90bf469590e7e8034cb110f6":{
      "scriptId":"u30"},
    "1e50660b03ef45ae93203579c20fd9d1":{
      "scriptId":"u31"},
    "ba51f27205a246f2a137e92c69ceac7d":{
      "scriptId":"u32"},
    "c534b5e15ded4dddb6c7b716666b0508":{
      "scriptId":"u33"},
    "0a78bcc336ba4223a8bbff882473e76c":{
      "scriptId":"u34"},
    "4c9a7158499348d6aeca628002d0287f":{
      "scriptId":"u35"},
    "55d8cdb1c1704afc9b9870b6e2b84186":{
      "scriptId":"u36"},
    "b770f416bc83464a97e6e956887ee9bd":{
      "scriptId":"u37"},
    "600e8aaa93dc47c2881004e1266b82c9":{
      "scriptId":"u38"},
    "2162e2b8b1b54a418cc8b34a58a64905":{
      "scriptId":"u39"},
    "94674d0d2485448b85ff7c021c2ae1a0":{
      "scriptId":"u40"},
    "078229d16f14480dae09274ab14a2e14":{
      "scriptId":"u41"},
    "1c300b4e05404371863212e8a1698afe":{
      "scriptId":"u42"},
    "d4405aee5e6a43ebb21370977c700e0e":{
      "scriptId":"u43"},
    "04307f70397340c1942ccd9011cd6a4b":{
      "scriptId":"u44"},
    "d7ab0b78fa2b42b7b30a5ee944389c12":{
      "scriptId":"u45"},
    "c37ec7c4e54d42679b6919b39abc1a55":{
      "scriptId":"u46"},
    "c3fda329fb5847179dc42fce3b2d9e1f":{
      "scriptId":"u47"},
    "3da9ae1b501d47eaac60e4c992ffb72b":{
      "scriptId":"u48"},
    "e651148b55b843a7b2fa7bf91e646a4d":{
      "scriptId":"u49"},
    "54049e757f444fe7a194ac68a08c47a2":{
      "scriptId":"u50"},
    "f340fda0584d47f1a9022f8358836065":{
      "scriptId":"u51"},
    "d5ac63f5d33640d1a9fb7ad25ca35594":{
      "scriptId":"u52"},
    "928be671ef87460c8ad73383cd7dd636":{
      "scriptId":"u53"},
    "dce6490910df485d8a510fdb6584b8e0":{
      "scriptId":"u54"},
    "a0aa6fa8de514fe8826dcb8571402467":{
      "scriptId":"u55"},
    "7fd782c715d44904b397fdd792c3c894":{
      "scriptId":"u56"},
    "ebec7cbc4dab4ee9b8f492a48bdf0038":{
      "scriptId":"u57"},
    "b375415126284aebbb349459679bfc73":{
      "scriptId":"u58"},
    "053b5e7f420849f3ad9223f37aefa16e":{
      "scriptId":"u59"},
    "24c6812ab6a94b838227cb02cb6b6bd4":{
      "scriptId":"u60"},
    "f1cc51ddfa8843ceb7614afb08f73966":{
      "scriptId":"u61"},
    "37286d220fdd4ab9b59100e748091b95":{
      "scriptId":"u62"},
    "335e4740547b4063aacaa257366fc6f9":{
      "scriptId":"u63"},
    "e6bd1080ee954b528ea8fe161a5981a8":{
      "scriptId":"u64"},
    "a3dbeb6ee75346f6806f481516d3d2aa":{
      "scriptId":"u65"},
    "d5d21d319fe642ccb89ca254820af7ca":{
      "scriptId":"u66"},
    "39d19c325a474a40a365f7d5b6508a88":{
      "scriptId":"u67"},
    "696ca86ed8934a578a155458074401f5":{
      "scriptId":"u68"},
    "50d3c23a580c40c9acb48bc548a7030c":{
      "scriptId":"u69"},
    "d2a104ef14864e4bb20bdc31a982bc96":{
      "scriptId":"u70"},
    "235282bc3cb14f349c33822719b2cfc0":{
      "scriptId":"u71"},
    "412441fb2d674dc28994691d2ad2e476":{
      "scriptId":"u72"},
    "8d720612ecad4609a9f3d69687a47fe2":{
      "scriptId":"u73"},
    "560dd90310464e43885d1b192d9b9d40":{
      "scriptId":"u74"},
    "0f23af05854048bb989838560d591cdb":{
      "scriptId":"u75"},
    "eff99bb8ebac40db93c9047feffd8097":{
      "scriptId":"u76"},
    "5824b93622994e9490b311aa3cf28b08":{
      "scriptId":"u77"}}});