//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EffectEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EffectEditorTYPE            129
#define IDR_BEZIER_TOOLS                130
#define IDR_TOOL_BAR                    131
#define IDD_TIME_BAR_CTRL               132
#define IDD_BEZIER_CONTROL              133
#define IDD_COLOR_BAR                   134
#define IDD_TOOLS_PANEL                 135
#define IDD_ADD_EDIT_CLIP               136
#define IDD_ANI_EFFECT_PROP             137
#define IDD_ANI_PIC_PROP                138
#define IDD_DIALOG1                     139
#define IDD_EFFECT_PROP                 140
#define IDD_PARTICLE_PROP               141
#define IDD_PROP_COLOR                  142
#define IDD_PROP_CURVE                  143
#define IDD_ROLE_PROP                   144
#define IDD_TAB_PROP                    145
#define IDD_NEW_FILE_TYPE_DIALOG        146
#define IDD_AUDIO_PROP                  147
#define IDC_BZ_EDIT_X                   1000
#define IDC_BZ_EDIT_Y                   1001
#define IDC_BZ_COMBO_FILTER             1002
#define IDC_BZ_STATIC_FILTER            1003
#define IDC_BZ_X                        1004
#define IDC_BZ_Y                        1005
#define IDC_ADD_CLIP                    1006
#define IDC_COMBO_EFFECTTYPE            1007
#define IDC_FILE_PATH                   1008
#define IDC_BROUSE                      1009
#define IDC_COMBO_LAYER                 1010
#define IDC_START_FRAME                 1011
#define IDC_COMBO_PLAYMODE              1012
#define IDC_TIME                        1013
#define IDC_CHECK_COLOR                 1014
#define IDC_COLOR_BUTTON                1015
#define IDC_FILE_NAME                   1016
#define IDC_EDIT_FPS                    1017
#define IDC_PLAY_ONE_TIME               1018
#define IDC_BUTTON_COLOR                1019
#define IDC_CHECK_BIND_TYPE             1020
#define IDC_BUTTON_SELECT_COLOR         1021
#define IDC_SLIDER_ALPHA                1022
#define IDC_EDIT_ALPHA                  1023
#define IDC_POS_BUTTON                  1025
#define IDC_SCAL_BUTTON                 1026
#define IDC_ROTATION_BUTTON             1027
#define IDC_IS_SPEC                     1028
#define IDC_ALPHA_BUTTON                1029
#define IDC_EDIT_INPUT                  1030
#define IDC_TOTAL_FRAME                 1031
#define IDC_TOTAL_TIME                  1032
#define IDC_COMBO_WORK_MODE             1033
#define IDC_EDIT_SAMPLE_COUNT           1034
#define IDC_STATIC_SAMPLE_COUNT         1035
#define IDC_BUTTON_RESET                1036
#define IDC_CHECK_SHOW_ROLE             1037
#define IDC_TAB                         1038
#define IDC_COMBO_MODEL                 1039
#define IDC_COMBO_COMPONENT             1040
#define IDC_COMBO_ACTION                1041
#define IDC_FRAME_COUNT                 1042
#define IDC_BUTTON_LAYER                1043
#define IDC_RADIO_SD_0                  1044
#define IDC_RADIO_SD_1                  1045
#define IDC_RADIO_SD_2                  1046
#define IDC_RADIO_SD_3                  1047
#define IDC_RADIO_SD_4                  1048
#define IDC_RADIO_SD_5                  1049
#define IDC_RADIO_SD_6                  1050
#define IDC_RADIO_SD_7                  1051
#define IDC_STATIC_TOTAL_TIME           1052
#define IDC_NEW_FILE_TYPE_LIST          1053
#define IDC_STATIC_LAYER                1054
#define IDC_COMBO_DIV_LAYER             1055
#define IDC_SLIDER_MAX_V                1056
#define IDC_SLIDER_MIN_V                1057
#define IDC_SLIDER_MAX_F                1058
#define IDC_SLIDER_MIN_F                1059
#define IDC_EDIT_MAX_V                  1060
#define IDC_EDIT_MIN_V                  1061
#define IDC_EDIT_MAX_F                  1062
#define IDC_EDIT_MIN_F                  1063
#define ID_BUTTON_PLAY                  32771
#define ID_BUTTON_PAUSE                 32772
#define ID_BUTTON_STOP                  32773
#define ID_BZ_TOOL_ARROW                32774
#define ID_BZ_TOOL_ADD                  32775
#define ID_BZ_TOOL_REMOVE               32776
#define ID_BZ_TOOL_CONVERT              32777
#define ID_TOOL_ARROW                   32778
#define ID_TOOL_BOUNDS_RECT             32779
#define ID_TOOL_MOVE                    32780
#define ID_TOOL_FRAME_POS               32781
#define ID_TOOL_FRAME_ROTATE            32782
#define ID_TOOL_FRAME_SIZE              32783
#define ID_ADD_A_CLIP                   32784
#define ID_NEXT_FRAME                   32785
#define ID_PREV_FRAME                   32786
#define ID_PLAY_STOP                    32787
#define ID_LEFT_KEY_DOWN                32788
#define ID_RIGHT_KEY_DOWN               32789
#define ID_UP_KEY_DOWN                  32790
#define ID_DOWN_KEY_DOWN                32791
#define ID_FILE_EXPORT                  32792
#define ID_SHOW_CENTER_CROSS            32793
#define ID_SHOW_BOX                     32794
#define ID_CLIP_CENTER                  32795
#define ID_32796                        32796
#define ID_BACKGROUND_COLOR             32797
#define ID_BACKGROUND_PICTURE           32798
#define ID_SHOW_BACKGROUND_COLOR        32799
#define ID_SHOW_BACKGROUND_PICTURE      32800
#define ID_REFRESH                      32801
#define ID_BATCH_EXPORT                 32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
