$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1429602387706.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"8eb1c5a9db6747c38698304382c9b13c",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9994d1c1804f4af1a45e4dfa9a03ef07",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":130},
            "size":{
              "width":690,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33d3f6906489464da52e65ef3f733186",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":130},
                "size":{
                  "width":690,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"361aae24ef244ff9af7a9895dc4093b9",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.647058823529412}}}},
            "location":{
              "x":710,
              "y":240},
            "size":{
              "width":245,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dad8114e54914264acc18a145f3682a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "outerShadow":{
                      "on":true,
                      "offsetX":0,
                      "offsetY":0,
                      "blurRadius":5,
                      "color":{
                        "r":255,
                        "g":0,
                        "b":0,
                        "a":0.647058823529412}}}},
                "location":{
                  "x":710,
                  "y":240},
                "size":{
                  "width":245,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/border_u2.png",
            "selected~":"images/登陆/border_u2_selected.png"}},
{
          "id":"a8415eff6f2c48db929dc4b1dda8007b",
          "label":"user_id",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":713,
              "y":243},
            "size":{
              "width":240,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 border = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["361aae24ef244ff9af7a9895dc4093b9"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 当前部件 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 border = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["361aae24ef244ff9af7a9895dc4093b9"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "placeholderText":"请输入登录账号"},
{
          "id":"372f6a0e66204e77877c5ee192f8c167",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.647058823529412}}}},
            "location":{
              "x":710,
              "y":300},
            "size":{
              "width":245,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c48eee3fda4698af9bff88cf844eea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "outerShadow":{
                      "on":true,
                      "offsetX":0,
                      "offsetY":0,
                      "blurRadius":5,
                      "color":{
                        "r":255,
                        "g":0,
                        "b":0,
                        "a":0.647058823529412}}}},
                "location":{
                  "x":710,
                  "y":300},
                "size":{
                  "width":245,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/border_u2.png",
            "selected~":"images/登陆/border_u2_selected.png"}},
{
          "id":"ea296db949964a4aa790f3cd535da132",
          "label":"user_pw",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":713,
              "y":303},
            "size":{
              "width":240,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 border = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["372f6a0e66204e77877c5ee192f8c167"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 当前部件 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 border = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["372f6a0e66204e77877c5ee192f8c167"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "placeholderText":"请输入登录密码"},
{
          "id":"836c67018e83430ca3a674a95fcbc2ce",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":375},
            "size":{
              "width":117,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "9994d1c1804f4af1a45e4dfa9a03ef07":{
      "scriptId":"u0"},
    "33d3f6906489464da52e65ef3f733186":{
      "scriptId":"u1"},
    "361aae24ef244ff9af7a9895dc4093b9":{
      "scriptId":"u2"},
    "dad8114e54914264acc18a145f3682a9":{
      "scriptId":"u3"},
    "a8415eff6f2c48db929dc4b1dda8007b":{
      "scriptId":"u4"},
    "372f6a0e66204e77877c5ee192f8c167":{
      "scriptId":"u5"},
    "c9c48eee3fda4698af9bff88cf844eea":{
      "scriptId":"u6"},
    "ea296db949964a4aa790f3cd535da132":{
      "scriptId":"u7"},
    "836c67018e83430ca3a674a95fcbc2ce":{
      "scriptId":"u8"}}});