
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 此头文件包含当前名字空间下的所有协议。要注意，如果把实现写在头文件里面，
// 包含这个头文件很容易产生循环。

#include "openau/AuAnyLogin.hpp"
#include "openau/DataBetweenAuAnyAndClient.hpp"
#include "openau/DataBetweenAuAnyAndGS.hpp"
#include "openau/QueryOrderRequest.hpp"
#include "openau/QueryOrderResponse.hpp"
#include "openau/RegistGameServerRequest.hpp"
#include "openau/RegistGameServerResponse.hpp"
#include "openau/ServerIDResponse.hpp"
