$axure.loadCurrentPage({
  "url":"主界面.html",
  "generationDate":new Date(1429602386214.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"c19ff7bbad704e1aa83a8da6a88e3c47",
    "type":"Axure:Page",
    "name":"主界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c8c3616478a41ac82a2738255f49f7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97a63569811e4ef9bb84aae04ff57bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"bec138dd23564988b9f18feddd59772a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3a168493cc1434fb6996c66d45ed020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宠物界面",
                      "target":{
                        "targetType":"page",
                        "url":"宠物界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"b517944c0f4a4b0880c78c0822c9143e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"163c6d0976e047ceb106824112e28ac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 人物属性",
                      "target":{
                        "targetType":"page",
                        "url":"人物属性.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"be42aed9706a4698a999ed92a708853c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfe41397ec3945308103411cde49e3b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a47174da33964db1921ff1c14377c990",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12aab2feb0164afcbcbbd5d404f9a1b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"378fa4e5e0fc4d68a61b6c2f410729e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56013885fcf044d99391416019d41a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u10.png"}},
{
          "id":"87d99d8b056544699ba9d89f78e419fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db88d4cb12a24003b48592b9026e7053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"c45a7c17dfe4405f8c530f45ea5efacc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a39b56fd8764900aa3ed9666bb674d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"c2c1a5cd87f84ab19ef5cd3355cf2eb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":280},
            "size":{
              "width":216,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3e3790ae764e0fafeb1810f386f856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":280},
                "size":{
                  "width":216,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"8da2eb05166942119220789a6191237d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":240},
            "size":{
              "width":109,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"dd5ac0754f934e6da461cf0d3571e114",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":240},
            "size":{
              "width":105,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组队界面（无队伍）",
                      "target":{
                        "targetType":"page",
                        "url":"组队界面（无队伍）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"633a9547464b45eaac46db8dcc7856e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7062567fe37f4671b1417f6950bb875c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"2547684663974b8da2890f07440d68df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507ba9df6a03449da65d45e84e0569a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"c64950414abd45718f1b4437c6ef121b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af2a43181eb4ca2be322ffd02deaae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"5b5033b180c94149ac6b762c37b30908",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9138d262fcb4662a6064769dc9d54fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":250},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"7eb719d31f344124972718c2180d164a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30104eb9c84247a3bd3f8962bd793d40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"2f4e1afbf0b64ea58a7aa8d1158ed4d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b68ed59e164241b591e17a33fef347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"17928333ccf844d29392f5c0124545bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d4f36e461f4c1195680c9f25d0f934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"33e0c8d3aed6489698b19f875883490b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"193ab656a3bf4781b0588018272bf0e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"23671f5012ca44c79e3514d9d7fd45f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":558},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbba446bbada448091139bb16e13a8c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":558},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 背包功能",
                      "target":{
                        "targetType":"page",
                        "url":"背包功能.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"70655d63ff544ceb999ae2383c7b966c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89bb42655db34d7fa8c52df0702b715a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"813c8f86c76549f5b3bc4a39d560ec25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd079a32d2d84f39a00cbc75633b969e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"7a63e741ed6b4420b532ed3ac4829cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8be1e95966164c31a737d74fdb515c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"4424809f6b984aeb9bab37fdd3d63435",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":136},
            "size":{
              "width":115,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf0f9d4d8b046399e810fc5958088c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":136},
                "size":{
                  "width":115,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u44.png"}},
{
          "id":"aca720404741471e9b8c65cccb626a15",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6ccbdf9a46f47f78ab333576ff99ac6",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":570},
            "size":{
              "width":328,
              "height":168}},
          "adaptiveStyles":{
}},
{
          "id":"915685482fd74fd5b9011c637810526e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deda536764d3401783310cdd6996b4ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"458c4f6fffd54df08656607219b82ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4632cd8707fd415c8885a2eb38b273e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"f295f4c1c9c549f6a6ac631cbca5d713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b80e5deaa446108b0a14db681fc54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"b99b479f0ff4484298953de4929efc11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49bd81647509432a818051af7f552072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"4d45687f87894bf29a1eaf451b603b7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daffd6d5b16e400e9e044c5da0f7b24d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"d853a0a22d8f482aa76d03f52406ad09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":171},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfbcfcd4595548cba3a89740767bd5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":171},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"a3c324d2b93748e590430444e4afe547",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":111},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf9694d1c3649c1b8439cee01fb4ae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":111},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"05676aeac5f94052a9e9957809186cfd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":280},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77920efb1bff42fc9f5e235ba631f3ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":280},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗布局",
                      "target":{
                        "targetType":"page",
                        "url":"战斗布局.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"8f4a1dafe5cd4c59a11ecfbb3a3f29e3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":320},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5dafbfc3e1740c3bac35bef6ad2b5a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":320},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"e29ccb2810114a40bd2c2f9926724550",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":360},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bc3d07df26549219dfc321313e1bc37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":360},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"e0237d3e55924f9ab5e1497382780a3d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":400},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0bdf58d2922485cadcde5a1ba73fe05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":400},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"be7319f18a7d413fa3ed8b21029e325a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":440},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"060253422156466f8e1d289a365eee87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":440},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"062d476879ad4560a1c0a30454a5fbd3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":570},
            "size":{
              "width":40,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026482e512e4467aa2995fd24a570e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":570},
                "size":{
                  "width":40,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天放大",
                      "target":{
                        "targetType":"page",
                        "url":"聊天放大.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u72.png"}},
{
          "id":"414dc6f1c35a4f46bf187fbf4f875435",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":1156,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05bb3539ac7645b59f18d11683035aa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":1156,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 功能缩放",
                      "target":{
                        "targetType":"page",
                        "url":"功能缩放.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"4c25099590394fa2a0e33d46adb74a5f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":605,
              "y":114},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面清屏",
                      "target":{
                        "targetType":"page",
                        "url":"主界面清屏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5c8c3616478a41ac82a2738255f49f7e":{
      "scriptId":"u0"},
    "97a63569811e4ef9bb84aae04ff57bed":{
      "scriptId":"u1"},
    "bec138dd23564988b9f18feddd59772a":{
      "scriptId":"u2"},
    "d3a168493cc1434fb6996c66d45ed020":{
      "scriptId":"u3"},
    "b517944c0f4a4b0880c78c0822c9143e":{
      "scriptId":"u4"},
    "163c6d0976e047ceb106824112e28ac9":{
      "scriptId":"u5"},
    "be42aed9706a4698a999ed92a708853c":{
      "scriptId":"u6"},
    "bfe41397ec3945308103411cde49e3b2":{
      "scriptId":"u7"},
    "a47174da33964db1921ff1c14377c990":{
      "scriptId":"u8"},
    "12aab2feb0164afcbcbbd5d404f9a1b1":{
      "scriptId":"u9"},
    "378fa4e5e0fc4d68a61b6c2f410729e3":{
      "scriptId":"u10"},
    "56013885fcf044d99391416019d41a10":{
      "scriptId":"u11"},
    "87d99d8b056544699ba9d89f78e419fe":{
      "scriptId":"u12"},
    "db88d4cb12a24003b48592b9026e7053":{
      "scriptId":"u13"},
    "c45a7c17dfe4405f8c530f45ea5efacc":{
      "scriptId":"u14"},
    "3a39b56fd8764900aa3ed9666bb674d7":{
      "scriptId":"u15"},
    "c2c1a5cd87f84ab19ef5cd3355cf2eb8":{
      "scriptId":"u16"},
    "8c3e3790ae764e0fafeb1810f386f856":{
      "scriptId":"u17"},
    "8da2eb05166942119220789a6191237d":{
      "scriptId":"u18"},
    "dd5ac0754f934e6da461cf0d3571e114":{
      "scriptId":"u19"},
    "633a9547464b45eaac46db8dcc7856e6":{
      "scriptId":"u20"},
    "7062567fe37f4671b1417f6950bb875c":{
      "scriptId":"u21"},
    "2547684663974b8da2890f07440d68df":{
      "scriptId":"u22"},
    "507ba9df6a03449da65d45e84e0569a3":{
      "scriptId":"u23"},
    "c64950414abd45718f1b4437c6ef121b":{
      "scriptId":"u24"},
    "9af2a43181eb4ca2be322ffd02deaae3":{
      "scriptId":"u25"},
    "5b5033b180c94149ac6b762c37b30908":{
      "scriptId":"u26"},
    "f9138d262fcb4662a6064769dc9d54fa":{
      "scriptId":"u27"},
    "7eb719d31f344124972718c2180d164a":{
      "scriptId":"u28"},
    "30104eb9c84247a3bd3f8962bd793d40":{
      "scriptId":"u29"},
    "2f4e1afbf0b64ea58a7aa8d1158ed4d0":{
      "scriptId":"u30"},
    "59b68ed59e164241b591e17a33fef347":{
      "scriptId":"u31"},
    "17928333ccf844d29392f5c0124545bf":{
      "scriptId":"u32"},
    "f9d4f36e461f4c1195680c9f25d0f934":{
      "scriptId":"u33"},
    "33e0c8d3aed6489698b19f875883490b":{
      "scriptId":"u34"},
    "193ab656a3bf4781b0588018272bf0e4":{
      "scriptId":"u35"},
    "23671f5012ca44c79e3514d9d7fd45f6":{
      "scriptId":"u36"},
    "dbba446bbada448091139bb16e13a8c3":{
      "scriptId":"u37"},
    "70655d63ff544ceb999ae2383c7b966c":{
      "scriptId":"u38"},
    "89bb42655db34d7fa8c52df0702b715a":{
      "scriptId":"u39"},
    "813c8f86c76549f5b3bc4a39d560ec25":{
      "scriptId":"u40"},
    "cd079a32d2d84f39a00cbc75633b969e":{
      "scriptId":"u41"},
    "7a63e741ed6b4420b532ed3ac4829cd9":{
      "scriptId":"u42"},
    "8be1e95966164c31a737d74fdb515c37":{
      "scriptId":"u43"},
    "4424809f6b984aeb9bab37fdd3d63435":{
      "scriptId":"u44"},
    "5bf0f9d4d8b046399e810fc5958088c4":{
      "scriptId":"u45"},
    "aca720404741471e9b8c65cccb626a15":{
      "scriptId":"u46"},
    "b6ccbdf9a46f47f78ab333576ff99ac6":{
      "scriptId":"u47"},
    "915685482fd74fd5b9011c637810526e":{
      "scriptId":"u48"},
    "deda536764d3401783310cdd6996b4ab":{
      "scriptId":"u49"},
    "458c4f6fffd54df08656607219b82ba3":{
      "scriptId":"u50"},
    "4632cd8707fd415c8885a2eb38b273e8":{
      "scriptId":"u51"},
    "f295f4c1c9c549f6a6ac631cbca5d713":{
      "scriptId":"u52"},
    "45b80e5deaa446108b0a14db681fc54e":{
      "scriptId":"u53"},
    "b99b479f0ff4484298953de4929efc11":{
      "scriptId":"u54"},
    "49bd81647509432a818051af7f552072":{
      "scriptId":"u55"},
    "4d45687f87894bf29a1eaf451b603b7a":{
      "scriptId":"u56"},
    "daffd6d5b16e400e9e044c5da0f7b24d":{
      "scriptId":"u57"},
    "d853a0a22d8f482aa76d03f52406ad09":{
      "scriptId":"u58"},
    "bfbcfcd4595548cba3a89740767bd5ab":{
      "scriptId":"u59"},
    "a3c324d2b93748e590430444e4afe547":{
      "scriptId":"u60"},
    "bdf9694d1c3649c1b8439cee01fb4ae7":{
      "scriptId":"u61"},
    "05676aeac5f94052a9e9957809186cfd":{
      "scriptId":"u62"},
    "77920efb1bff42fc9f5e235ba631f3ed":{
      "scriptId":"u63"},
    "8f4a1dafe5cd4c59a11ecfbb3a3f29e3":{
      "scriptId":"u64"},
    "f5dafbfc3e1740c3bac35bef6ad2b5a5":{
      "scriptId":"u65"},
    "e29ccb2810114a40bd2c2f9926724550":{
      "scriptId":"u66"},
    "9bc3d07df26549219dfc321313e1bc37":{
      "scriptId":"u67"},
    "e0237d3e55924f9ab5e1497382780a3d":{
      "scriptId":"u68"},
    "f0bdf58d2922485cadcde5a1ba73fe05":{
      "scriptId":"u69"},
    "be7319f18a7d413fa3ed8b21029e325a":{
      "scriptId":"u70"},
    "060253422156466f8e1d289a365eee87":{
      "scriptId":"u71"},
    "062d476879ad4560a1c0a30454a5fbd3":{
      "scriptId":"u72"},
    "026482e512e4467aa2995fd24a570e2d":{
      "scriptId":"u73"},
    "414dc6f1c35a4f46bf187fbf4f875435":{
      "scriptId":"u74"},
    "05bb3539ac7645b59f18d11683035aa9":{
      "scriptId":"u75"},
    "4c25099590394fa2a0e33d46adb74a5f":{
      "scriptId":"u76"}}});