$axure.loadCurrentPage({
  "url":"地图界面.html",
  "generationDate":new Date(1429602387027.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"62d4c80293aa493fa8da62e6d523ff4a",
    "type":"Axure:Page",
    "name":"地图界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12f55c4b050744c8969b9675e5b99c0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d39103b1df504e198debf7039dbb8b53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"0a86e756fab146cebb59d76a3a5b0114",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d52111ec07c4438833efc65a21a6aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"8a1f92fd2d0e4e018493fe07603e3b7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd780a095dc64124a3bbcbf4674fea5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"ec7626077cac4a958e4e27e8678c3b50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaf61bc86bc44f87950851a3a4ddfee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"b30d6503f47648659239f80ec41eecca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc90a1f48614926aea0f68dd30ac4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"1fbb7b5ac18d4b05a5a4ba22dd47d2b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af43134be1d349e39ca0e143a26a447a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u10.png"}},
{
          "id":"206286e6f02146e4a70a7a649aa591ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bac454fce9e4d27b528b86217d01ca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"636275d35f7249dbbe2f4d5d2965d6db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443a868140ed470b90c0bc847c2fab49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"4689acd121444f29bcf4c3feaeb02874",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":280},
            "size":{
              "width":216,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944f0520c5844376a58a23dcf45fe9a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":280},
                "size":{
                  "width":216,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"401317813eb14dd887257a3efe0d2cbf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":240},
            "size":{
              "width":109,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"9c480485f9e9427d8cc74885cb431218",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":240},
            "size":{
              "width":105,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"5076660a1d7c4e088af7a193275f6793",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8989c18db1345919a36555e1b4c4b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"5da4bff48cb6476d95e705b02b005558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57697532c1e442e9965d8a967c9fd6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"dac5c79b2e6a41608eb4e361faf38e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d93c8da4ed46f39b7e0dd940a70827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"52ae495d6a334bc4a0e272877951fafd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7b4ccb59b9448699ce62f4bb9cca6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":250},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"1830bb03df5f487f9884057f2d438b77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b414e1506a4f869b9db59f67572a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"1cdfcc083093443b8edc35a85a8edfa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5d47fd7ac24f67a0d2afb674c5212b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"ceca58d21e9841ffa95ea4e248f8c8d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40798c58e88340a991629cf26ba4a00b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"d7e2c711d0da4e41bc09ab7bbf07f8bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4a97eb09f14a63a0d31cdec224c930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"cf5bce39c7464dc397536f8b49ea6216",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":558},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798a8fd60353487f920bed27f30f1591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":558},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"c551035e76b64548b0ec8dd0acbe33fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fdac70917b84a7fa2d794b76ba11ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"4f552178b95840749be14b3ab703faa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f53b19b3aef940d585ff6b56fa261c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"42ffb13ae3154d8aa28feebdea5157d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d47ee6678641908a3ea684254decd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"ca170419a10b45c086f7268821719b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":136},
            "size":{
              "width":115,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3478e5b29a743619f39214df21af80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":136},
                "size":{
                  "width":115,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u44.png"}},
{
          "id":"5be71e2660c944359480a7d513c95dc0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aed9653ae7f7436da64fd0d52d357f58",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":570},
            "size":{
              "width":328,
              "height":168}},
          "adaptiveStyles":{
}},
{
          "id":"1db3c6d1cc664cd2a208ca44442b4697",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54214dda32244b7cb3a32e038e3f7192",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"7800003e43254263a7b0b9fbca6cf4b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd55bf0d39e4e03a2edbd6f2337885b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"f9cb1d3439fb42109f1cef99abe7ecd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb74ba67c5147ad9c579bca73c26b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"38d7ca15b1a24f6596562b887b14caf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99093c6f85a542f5bada1d1fd7237798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"9eef2bb9537e40a996d3291e3ae0256e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ced28a98f5d14f0fafaeb3b4e46c9b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"702108f03f77422c9058b8dcc61fbc79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":171},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a2fdb0ebb19452a881e8a18437791fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":171},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"4b068fbed3a44cb3a9afcf256f6a0266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":111},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7b3e77af32642f5bd7addadfd0bf748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":111},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"12d78f455f4649c6908be00ceb78fac2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":280},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6ed1818b0c498394e147cabdf85272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":280},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"2c6a5fb5262b4b2eb89542233e2bbb57",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":320},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c39f59efd16b44fbb056838a7798dc40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":320},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"9a51b7b9d226403e847cf6620a5f5b30",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":360},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e15ab03dfe4e158bd307b47501f4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":360},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"058639d6662f49efbd47ca8ddb8ae642",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":400},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274ddba3f7ea4f5ea5b29c116ddadd4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":400},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"a4389bf4c87e4ca4a37cd0c7649f4452",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":440},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2863f924d0d4b6caf7563285d6937b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":440},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"70acdd73d55a4990b0fd85852737c620",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":300,
              "y":230},
            "size":{
              "width":750,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3adfe3fe68fa4f7c997fea0d431f497e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":300,
                  "y":230},
                "size":{
                  "width":750,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/地图界面/u72.png"}},
{
          "id":"e87e07cd21c5485fac1a01f64c2a8149",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02867ca115246bb9c3573efd6a40f7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/宠物界面/u74.png"}},
{
          "id":"50ad4ae9f48d466ab462a385e14dc3af",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":1156,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b6e82cb74646a3ad4912937c9903cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":1156,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "12f55c4b050744c8969b9675e5b99c0e":{
      "scriptId":"u0"},
    "d39103b1df504e198debf7039dbb8b53":{
      "scriptId":"u1"},
    "0a86e756fab146cebb59d76a3a5b0114":{
      "scriptId":"u2"},
    "2d52111ec07c4438833efc65a21a6aec":{
      "scriptId":"u3"},
    "8a1f92fd2d0e4e018493fe07603e3b7c":{
      "scriptId":"u4"},
    "cd780a095dc64124a3bbcbf4674fea5b":{
      "scriptId":"u5"},
    "ec7626077cac4a958e4e27e8678c3b50":{
      "scriptId":"u6"},
    "aaf61bc86bc44f87950851a3a4ddfee2":{
      "scriptId":"u7"},
    "b30d6503f47648659239f80ec41eecca":{
      "scriptId":"u8"},
    "5fc90a1f48614926aea0f68dd30ac4ae":{
      "scriptId":"u9"},
    "1fbb7b5ac18d4b05a5a4ba22dd47d2b5":{
      "scriptId":"u10"},
    "af43134be1d349e39ca0e143a26a447a":{
      "scriptId":"u11"},
    "206286e6f02146e4a70a7a649aa591ad":{
      "scriptId":"u12"},
    "3bac454fce9e4d27b528b86217d01ca1":{
      "scriptId":"u13"},
    "636275d35f7249dbbe2f4d5d2965d6db":{
      "scriptId":"u14"},
    "443a868140ed470b90c0bc847c2fab49":{
      "scriptId":"u15"},
    "4689acd121444f29bcf4c3feaeb02874":{
      "scriptId":"u16"},
    "944f0520c5844376a58a23dcf45fe9a4":{
      "scriptId":"u17"},
    "401317813eb14dd887257a3efe0d2cbf":{
      "scriptId":"u18"},
    "9c480485f9e9427d8cc74885cb431218":{
      "scriptId":"u19"},
    "5076660a1d7c4e088af7a193275f6793":{
      "scriptId":"u20"},
    "f8989c18db1345919a36555e1b4c4b35":{
      "scriptId":"u21"},
    "5da4bff48cb6476d95e705b02b005558":{
      "scriptId":"u22"},
    "57697532c1e442e9965d8a967c9fd6ef":{
      "scriptId":"u23"},
    "dac5c79b2e6a41608eb4e361faf38e9c":{
      "scriptId":"u24"},
    "c1d93c8da4ed46f39b7e0dd940a70827":{
      "scriptId":"u25"},
    "52ae495d6a334bc4a0e272877951fafd":{
      "scriptId":"u26"},
    "f7b4ccb59b9448699ce62f4bb9cca6d0":{
      "scriptId":"u27"},
    "1830bb03df5f487f9884057f2d438b77":{
      "scriptId":"u28"},
    "20b414e1506a4f869b9db59f67572a97":{
      "scriptId":"u29"},
    "1cdfcc083093443b8edc35a85a8edfa7":{
      "scriptId":"u30"},
    "1a5d47fd7ac24f67a0d2afb674c5212b":{
      "scriptId":"u31"},
    "ceca58d21e9841ffa95ea4e248f8c8d1":{
      "scriptId":"u32"},
    "40798c58e88340a991629cf26ba4a00b":{
      "scriptId":"u33"},
    "d7e2c711d0da4e41bc09ab7bbf07f8bf":{
      "scriptId":"u34"},
    "5c4a97eb09f14a63a0d31cdec224c930":{
      "scriptId":"u35"},
    "cf5bce39c7464dc397536f8b49ea6216":{
      "scriptId":"u36"},
    "798a8fd60353487f920bed27f30f1591":{
      "scriptId":"u37"},
    "c551035e76b64548b0ec8dd0acbe33fe":{
      "scriptId":"u38"},
    "8fdac70917b84a7fa2d794b76ba11ec8":{
      "scriptId":"u39"},
    "4f552178b95840749be14b3ab703faa8":{
      "scriptId":"u40"},
    "f53b19b3aef940d585ff6b56fa261c5b":{
      "scriptId":"u41"},
    "42ffb13ae3154d8aa28feebdea5157d8":{
      "scriptId":"u42"},
    "c4d47ee6678641908a3ea684254decd3":{
      "scriptId":"u43"},
    "ca170419a10b45c086f7268821719b5f":{
      "scriptId":"u44"},
    "c3478e5b29a743619f39214df21af80c":{
      "scriptId":"u45"},
    "5be71e2660c944359480a7d513c95dc0":{
      "scriptId":"u46"},
    "aed9653ae7f7436da64fd0d52d357f58":{
      "scriptId":"u47"},
    "1db3c6d1cc664cd2a208ca44442b4697":{
      "scriptId":"u48"},
    "54214dda32244b7cb3a32e038e3f7192":{
      "scriptId":"u49"},
    "7800003e43254263a7b0b9fbca6cf4b0":{
      "scriptId":"u50"},
    "4bd55bf0d39e4e03a2edbd6f2337885b":{
      "scriptId":"u51"},
    "f9cb1d3439fb42109f1cef99abe7ecd6":{
      "scriptId":"u52"},
    "cbb74ba67c5147ad9c579bca73c26b85":{
      "scriptId":"u53"},
    "38d7ca15b1a24f6596562b887b14caf2":{
      "scriptId":"u54"},
    "99093c6f85a542f5bada1d1fd7237798":{
      "scriptId":"u55"},
    "9eef2bb9537e40a996d3291e3ae0256e":{
      "scriptId":"u56"},
    "ced28a98f5d14f0fafaeb3b4e46c9b9f":{
      "scriptId":"u57"},
    "702108f03f77422c9058b8dcc61fbc79":{
      "scriptId":"u58"},
    "9a2fdb0ebb19452a881e8a18437791fb":{
      "scriptId":"u59"},
    "4b068fbed3a44cb3a9afcf256f6a0266":{
      "scriptId":"u60"},
    "f7b3e77af32642f5bd7addadfd0bf748":{
      "scriptId":"u61"},
    "12d78f455f4649c6908be00ceb78fac2":{
      "scriptId":"u62"},
    "bd6ed1818b0c498394e147cabdf85272":{
      "scriptId":"u63"},
    "2c6a5fb5262b4b2eb89542233e2bbb57":{
      "scriptId":"u64"},
    "c39f59efd16b44fbb056838a7798dc40":{
      "scriptId":"u65"},
    "9a51b7b9d226403e847cf6620a5f5b30":{
      "scriptId":"u66"},
    "a9e15ab03dfe4e158bd307b47501f4c4":{
      "scriptId":"u67"},
    "058639d6662f49efbd47ca8ddb8ae642":{
      "scriptId":"u68"},
    "274ddba3f7ea4f5ea5b29c116ddadd4d":{
      "scriptId":"u69"},
    "a4389bf4c87e4ca4a37cd0c7649f4452":{
      "scriptId":"u70"},
    "b2863f924d0d4b6caf7563285d6937b7":{
      "scriptId":"u71"},
    "70acdd73d55a4990b0fd85852737c620":{
      "scriptId":"u72"},
    "3adfe3fe68fa4f7c997fea0d431f497e":{
      "scriptId":"u73"},
    "e87e07cd21c5485fac1a01f64c2a8149":{
      "scriptId":"u74"},
    "f02867ca115246bb9c3573efd6a40f7e":{
      "scriptId":"u75"},
    "50ad4ae9f48d466ab462a385e14dc3af":{
      "scriptId":"u76"},
    "44b6e82cb74646a3ad4912937c9903cd":{
      "scriptId":"u77"}}});