
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 这个包含所有的协议
// 当把实现写在头文件中时，很容易产生循环。这时，不要使用这个文件。

#include "ACAnswer2.hpp"
#include "ACPP.hpp"
#include "ACQuestion2.hpp"
#include "ACRemoteCode2.hpp"
#include "ACReport2.hpp"
#include "ACCaptcha.hpp"