
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include <set>
#include <map>
#include <list>
#include <vector>
#include "win32/share.hpp"

// provider id


namespace Defence { 
void RegisterProtocols();
void UnregisterProtocols();
} 
