#pragma once

enum
{
	ERR_CREATE_HTMLVIEW =				1,				// 创建HtmlView控件失败!
	ERR_LOAD_UIRESOURCE =				2,				// 加载Launcher资源包失败!
	ERR_START_UPDATE =					3,				// 无法启动更新(%1!lu!)!
	ERR_CLIENT_MAX_COUNT =				4,				// 同时打开的魔幻修仙客户端已达到上限：\n\n%1!s!\n\n
	ERR_START_CLIENT =					5,				// 启动客户端失败(%1!u!)，%2!s!(%3!u!)：\n\n\t%4!s!\n\n请尝试对客户端进行版本验证或重新安装客户端程序。
	ERR_START_CLIENT2 =					6,				// 启动客户端失败(%1!u!)：\n\n\t%2!s!\n\n请尝试对客户端进行版本验证或重新安装客户端程序。
	QST_STOP_UPDATE =					7,				// 更新过程正在修改本地文件！强行终止会导致文件内容被破坏，严重时可能还会导致程序无法正常启动。您确定要退出吗？
	QST_STOP_UPDATE2 =					8,				// 更新过程正在进行中！您确定要退出么？
	TIP_START_FROM_LAUNCHER =			9,				// 请从launcher启动,然后才能执行手动更新！
	TIP_SELECT_UPDATE_PATCH =			10,				// 魔幻修仙更新包(*.%1!s!)|*.%2!s!;*.zip|所有文件(*.*)|*.*||
	ERR_START_UPDATE_THREAD =			11,				// 更新失败！更新线程没有成功启动，请重新尝试.
	ERR_START_REPAIR =					12,				// 版本验证失败！没有成功启动版本验证工具，请重新尝试.
	ERR_CREATE_PROCESS =				13,				// 创建进程失败%1!s!:\n%2!s!
	TIP_BACKGROUND_UPDATING =			14,				// 正在进行后台更新。请放心，不会影响您当前的游戏进程！
	TIP_HAS_NEW_VERSION	=				15,				// 有新版本需要更新！
	TIP_ALREADY_NEW_VERSION =			16,				// 您的游戏客户端已经是最新版本！
	TIP_CLIENT_NOT_INTACT =				17,				// 您的客户端版本不完整,强烈建议您执行版本验证！
	TIP_HAS_NEW_VERSION2 =				18,				// 有新版本需要更新！\n请从launcher启动,然后才能执行版本更新！
	QST_AUTO_PATH_UPDATE =				19,				// 当前客户端版本需要下载大量数据以完成更新。\n\n点击&quot;是&quot;，我们的更新程序将尝试自动完成此次更新。\n点击&quot;否&quot;，更新程序尝试为你自动打开手动包下载页面。\n点击&quot;取消&quot;，您可以自己选择补丁包进行更新；\n\n自动更新完成后如果仍旧不是最新版本，将会提示你继续更新。\n自动更新需要时间较长，请耐心等待。
	TIP_PATCH_UPDATING =				20,				// 正在使用补丁包自动更新客户端...
	TIP_DEFAULT_UPDATING =				21,				// 正在自动更新客户端...
	QST_REPAIR =						22,				// 当前客户端存在问题！是否修复客户端？
	TIP_REPAIR_UPDATING =				23,				// 正在修复客户端...
	QST_ENFORCE_REPAIR =				24,				// 当前客户端已经是最新版本！是否使用该补丁包强制修复客户端？
	TIP_ENFORCE_REPAIRING =				25,				// 正在使用补丁包强制修复客户端...
	TIP_BACKGROUND_UPDATE_COMPLETE =	26,				// 后台更新完毕。
	TIP_UPDATE_SUCCESS =				27,				// 更新成功!
	ERR_BACKGROUND_UPDATE =				28,				// 后台更新失败！%1!s!(%2!ld!)
	ERR_UPDATE =						29,				// 更新失败！\n%1!s!(%2!ld!)
	ERR_PATCH_UPDATE =					30,				// 使用补丁包更新失败！\n%1!s!(%2!ld!)
	ERR_CANNOT_GET_NEW_VERSION =		31,				// 无法获知是否有新版本需要更新！\n%1!s!(%2!ld!)

	TOK_PRODUCT_NAME					= 40,			//	魔幻修仙
	TOK_PRODUCT_LAUNCHER				= 41,			//	魔幻修仙启动程序
	TOK_PRODUCT_PATCHER					= 42,			//	魔幻修仙更新程序
	TOK_PRODUCT_REPAIR					= 43,			//	魔幻修仙版本验证程序
	TOK_PRODUCT_CLIENT					= 44,			//	魔幻修仙客户端程序

	ERR_COMMIT =						100,			// 错误: Commit( %1!s! ) 失败!
	ERR_UNMOUNT =						101,			// 错误: Unmount( %1!s! ) 失败!
	TIP_MOUNT_ROOT =					102,			// 加载程序根系统...
	TIP_MOUNT_RESOURCE =				103,			// 加载资源子系统...
	ERR_MOUNT =							104,			// 错误: Mount( %1!s!, %2!s!) 失败! 
	TIP_REBUILD_FILE =					105,			// 尝试重建该文件.
	ERR_REBUILD =						106,			// 错误: 重建( %1!s! ) 失败!
	ERR_DOWNLOAD_FILE =					107,			// 错误: 下载文件失败 - %1!s!
	ERR_MOUNT_BRIEF =					108,			// 错误: Mount( %1!s!, %2!s!.brief) 失败!
	ERR_GETMETAINFO =					109,			// 错误: GetMetaInfos( %1!s! ) 失败!
	ERR_MOUNT_CACHE =					110,			// 错误: Mount( %1!s!, %2!s!.cache) 失败!
	TIP_DOWNLOAD_FILE_COUNT =			111,			// 共需下载 %1!lu! 个文件...
	TIP_DOWNLOAD_FILE_ERROR =			112,			// 已经发现有 %1!lu! 个文件连续下载失败! 我们放弃了后续文件.
	TIP_DOWNLOAD_COMPLETE =				113,			// 下载完毕。有 %1!lu! 个文件下载失败!
	TIP_DOWNLOAD_COMPLETE2 =			114,			// 下载完毕。共下载了 %1!lu! 个文件。
	ERR_REMOVE_FILE =					115,			// 错误: RemoveFile( %1!s!%2!s! ) 失败!
	ERR_FILE_NOT_INTACT =				116,			// 错误: 文件( %1!s!%2!s! )内容不完整,请尝试重新更新!
	ERR_CHECK_FILE =					117,			// 错误: CheckFile( %1!s! ) 失败!
	ERR_DECODE_FILE =					118,			// 错误: DecodeFile( %1!s! ) 失败!
	TIP_CHECK_FILE_COUNT =				119,			// 共 %1!lu! 个文件需要校验。
	TIP_MERGE_FILE_COUNT =				120,			// 共 %1!lu! 个文件需要合并。
	ERR_READ_FILE =						121,			// 错误: 读文件失败 - %1!s!%2!s!
	ERR_WRITE_FILE =					122,			// 错误: 写文件失败 - %1!s!%2!s!
	ERR_INVALID_FILE =					123,			// 错误: 无效文件(空文件) - %1!s!
	TIP_DOWNLOAD_PROGRESS =				124,			// 已下载：%1!d!%
	TIP_DOWNLOAD_CHILD_META_FILE =		125,			// 正在下载( %1!s! )子目录更新文件列表...

	ERR_INET_FILE_OPEN_FAILED =			150,			// 无法读取服务器文件(%1!s!)!
	TIP_INET_FILE_DOWNLOADED_ALREADY =	151,			// 文件已经下载完毕(%1!s!)!
	TIP_INET_FILE_DOWNLOADED_JUST_NOW =	152,			// 文件下载完毕(%1!s!)!
	TIP_INET_FILE_DOWNLOADED_PERCENT =	153,			// 已下载：(%1!lu!)
	ERR_INET_FILE_DATA_CHANGED =		154,			// 服务器文件数据已发生改变(%1!s!)!
	ERR_INET_FILE_SIZE_CHANGED =		155,			// 服务器文件大小已发生改变(%1!s!)!
	ERR_INET_FILE_DISCONNECT_FROM_SERVER =	156,		// 与服务器连接已断开，下载 %1!s! 失败!

	ERR_NATIVE_FILE_CREATE_FAILED =		160,			// 创建本地文件失败(%1!s!)!
	ERR_NATIVE_FILE_CACHE_CORRUPT =		161,			// 本地缓存文件已被破坏(%1!s!)，请重新下载!
	ERR_NATIVE_FILE_SEEK_FAILED =		162,			// 本地文件重定位失败(%1!s!)!

	TIP_DOWNLOAD_META_FILE =			200,			// 正在下载最新文件列表...
	ERR_DOWNLOAD_CHILD_META_FILE =		201,			// 下载子包MetaInfo文件失败！
	TIP_ANALYZE_CHILD_META_FILE =		202,			// 正在分析( %1!s!%2!s! )子目录文件列表...
	TIP_READ_CACHE_META_FILE =			203,			// 开始加载缓存MetaInfo文件...
	WRN_MISSING_DEFAULT_URL =			204,			// 警告: 缺少缺省更新服务器url!
	WRN_MISSING_BACKUP_URL =			205,			// 警告: 缺少备用更新服务器url!
	WRN_MISSING_DEFAULT_URL2 =			206,			// 警告: 使用缺省服务器url: %1!s!
	WRN_USE_SETTING_URL =				207,			// 警告: 使用配置文件提供的url: %1!s!
	WRN_USE_DEFAULT_VALUE =				208,			// 警告: 使用缺省值url: %1!s!
	TIP_INITIALIZING =					209,			// 正在初始化...
	ERR_CLIENT_IS_RUNNING =				210,			// 有&quot;魔幻修仙&quot;客户端程序正在运行，请首先退出该程序然后重新尝试！
	ERR_READ_LOCAL_SETUPMETA =			211,			// 读本地SetupMeta文件失败！
	TIP_LOAD_RUN_SYSTEM =				212,			// 加载运行系统...
	TIP_PREPARE_COMPLETE =				213,			// 完成准备过程！
	TIP_CHECK_LOCAL_VERSION =			214,			// 正在检查本地版本...
	ERR_READ_LOCAL_VERSION =			215,			// 无法读取本地安装程序版本信息！
	ERR_LOCAL_VERSION_NOT_INTACT =		216,			// 本地版本信息不完整(缺少更新服务器地址)！
	TIP_CHECK_SERVER_VERSION =			217,			// 正在检查服务器版本...
	ERR_GET_SERVER_VERSION =			218,			// 无法获得服务器新版本！
	ERR_CONNECT_TO_SERVER =				219,			// 无法连接到服务器！
	ERR_SERVER_VERSION_NOT_INTACT =		220,			// 新版本信息不完整(缺少更新服务器地址)！
	TIP_BACKGROUND_HAS_NEW_VERSION =	221,			// 检测到后台更新有新版本。
	TIP_HAS_NOT_UPDATE_VERSION =		222,			// 没有更新的版本需要更新
	TIP_NOT_FOUND_PATCH_URL =			223,			// 没有找到单独的补丁包自动更新地址，尝试缺省更新。
	TIP_NOT_FOUND_PATCH_METAFILE =		224,			// 没有找到补丁包描述文件用于自动更新，尝试缺省更新。
	TIP_NOT_FOUND_PATCH =				225,			// 没有找到合适的补丁包用于更新，尝试缺省更新。
	ERR_GET_SERVER_SETUPMETA =			226,			// 无法获得服务器SetupMeta文件！
	TIP_UPDATE_FILE_COUNT =				227,			// 统计更新项目完毕，共需更新 %1!lu! 项.
	TIP_DOWNLOAD_MERGE_FILE_COUNT =		228,			// 统计更新项目完毕，共需下载 %1!lu! 项，合并 %2!lu! 项.
	TIP_DOWNLOAD_FILE_COUNT2 =			229,			// 统计更新项目完毕，共需下载 %1!lu! 项.
	TIP_MERGE_FILE_COUNT2 =				230,			// 统计更新项目完毕，共需合并 %1!lu! 项.
	TIP_NEED_NOT_UPDATE =				231,			// 统计更新项目完毕，无需任何更新.
	TIP_ARRANGE_UPDATE_LIST =			232,			// 正在统计更新项目...
	TIP_DELETE_FILE_COUNT =				233,			// 统计更新项目完毕，共需删除 %1!lu! 项.
	TIP_SAVE_NEW_VERSION =				234,			// 保存最新版本信息...
	ERR_SAVE_NEW_VERSION =				235,			// 保存最新版本信息失败！
	TIP_SAVE_NEW_FILE_INFO =			236,			// 保存最新文件信息...
	ERR_SAVE_UPDATE_META_FILE =			237,			// 保存更新项目的MetaInfo文件失败！
	TIP_SAVE_UPDATE_META_FILE =			238,			// 保存更新项目的MetaInfo文件成功！
	TIP_START_DOWNLOAD =				239,			// 开始下载更新项目..
	ERR_DELETE_BRIEF_FOLDER =			240,			// 错误: 删除Brief临时文件夹失败 - %1!s!
	ERR_DOWNLOAD_UPDATE_ITEM =			241,			// 下载更新项目失败！
	TIP_DOWNLOAD_UPDATE_ITEM =			242,			// 下载更新项目成功完成！
	TIP_SAVE_CACHE_META_FILE =			243,			// 更新缓存中的MetaInfo信息...
	TIP_DELETE_FILE_COUNT2 =			244,			// 共 %1!lu! 个文件需要删除。
	ERR_DELETE_FILE =					245,			// 错误: 删除文件失败 - %1!s!
	TIP_START_CHECK_FILE =				246,			// 开始校验文件...
	TIP_CHECK_FILE_COMPLETE =			247,			// 校验完毕!
	ERR_CHECK_FILE2 =					248,			// 校验失败!查看日志可以确定没有通过校验的文件列表.
	TIP_START_MERGE_FILE =				249,			// 开始合并...
	ERR_MERGE_FILE_COUNT =				250,			// %1!lu! 个文件中 %2!lu! 个文件合并失败!
	TIP_MERGE_FILE_COMPLETE =			251,			// %1!lu! 个文件成功完成合并! 
	TIP_COMMITING =						252,			// 正在提交更新内容...
	ERR_SAVE_VERSION_FILE =				253,			// 错误: 更新版本文件 %1!s! 失败!
	TIP_COMMIT_PART_AND_REBOOT =		254,			// 完成部分提交！更新程序将自动重起完成后续更新!
	ERR_DOWNLOAD_PART =					255,			// 部分文件下载失败，请重新尝试！
	ERR_UPDATE_PART =					256,			// 部分文件没有完成更新，请重新尝试！
	TIP_COMMIT_COMPLETE =				257,			// 完成提交！
	ERR_COMMIT2 =						258,			// 提交失败！
	TIP_START_DESTROY =					259,			// 开始最后处理...
	TIP_START_DESTROY2 =				260,			// 正在进行部分更新的最后处理...
	TIP_DELETE_CACHE_FOLDER =			261,			// 清理临时目录...
	TIP_UPDATE_PART =					262,			// 完成部分更新,等待重启后继续更新...
	ERR_UPDATE2 =						263,			// 更新失败！

	ERR_PATCH_LIST_EMPTY =				300,			// 补丁包自动更新：补丁包列表为空！
	TIP_DOWNLOAD_PROGRESS2 =			301,			// 正在下载 %1(%2M)...
	TIP_CHECK_PATCH_FILE =				302,			// 正在检查下载成功的补丁包文件: %1!s!
	ERR_PATCH_FORMAT =					303,			// 补丁包格式不正确！
	ERR_READ_PATCH_VERSION =			304,			// 无法读取补丁包版本信息！
	ERR_PATCH_NOT_MATCH =				305,			// 该补丁包不适用更新本客户端，请根据当前客户端程序版本下载正确的补丁包后重试！
	ERR_PATCH_NOT_MATCH2 =				306,			// 该补丁包不适用更新本客户端!
	TIP_AUTO_PATH_UPDATING =			307,			// 正在应用补丁包进行自动更新。

	TIP_CHECKING_PATCH =				400,			// 正在检查差异包...
	ERR_READ_PATCH_SETUPMETA =			401,			// 读补丁包 .setup.meta 文件失败!
	ERR_LOAD_PATCH_DELETE_LIST =		402,			// 加载补丁包删除文件列表失败！
	TIP_LOAD_LOCAL_META_FILE =			403,			// 开始加载本地MetaInfo文件...
	ERR_LOAD_LOCAL_META_FILE =			404,			// 加载本地MetaInfo文件失败！
	ERR_LOAD_PATCH_META_FILE =			405,			// 加载补丁包MetaInfo文件失败！
	TIP_NO_FILE_UPDATE =				406,			// 没有文件需要更新.
	TIP_MERGE_DELETE_FILE_COUNT =		407,			// 统计更新项目完毕，共需合并 %1!lu! 项，共需删除 %2!lu! 项.

	TIP_SELECT_CHECK_ITEM =				500,			//请选择需要检测的项目
	TIP_CHECK_FILE_NOT_EXIST =			501,			//%1!s! 文件不存在，您需要至少执行两次版本验证完成客户端修复！\n第一次选择[程序文件]进行版本校验,校验完成后再选择其它资源包文件进行版本校验.
	ERR_AT_LEAST_SELECT_ONE_LINE =		502,			//至少要选择一行检测项目！
	QST_STOP_CHECK =					503,			//检测过程正在修改本地文件！强行终止会导致文件内容被破坏，严重时可能还会导致程序无法正常启动。您确定要退出吗？
	QST_STOP_CHECK2 =					504,			//检测过程正在进行中！您确定要退出么？
	TIP_SUCCESS_CHECK_ALL_FILES =		505,			//成功重置所有与服务器不一致文件！
	TIP_SUCCESS_CHECK_SELECT_FILES =	506,			//成功重置已选项目中与服务器不一致文件！
	ERR_CHECK =							507,			//检测失败！\n%1!s!(%2!ld!)
	ERR_CHECK_FILE_NOT_EXIST2 =			508,			//%1!s! 文件不存在或者为隐藏文件，请将该文件手工设为不隐藏后重试！
	TIP_PROGRAME_FILES =				509,			//程序文件
	ERR_START_DOWNLOAD =				510,			//无法启动下载！
	ERR_DOWNLOAD_ROOT_METAFILE =		511,			//下载服务器根目录文件列表失败！
	//重复定义 512,		//正在下载服务器子目录 %1!s! 文件列表...
	ERR_DOWNLOAD_CHILD_METAFILE =		513,			//下载服务器子目录 %1!s! 文件列表失败！
	TIP_DOWNLOAD_UPDATE_FILE =			514,			//检测完成，正在下载需要更新的文件...
	ERR_SAVE_LOCAL_SETUPMETA =			515,			//更新本地 SetupMeta 文件失败！
	TIP_REPAIR_COMPLETE =				516,			//版本验证完毕！
	ERR_REPAIR_RESULT =					517,			//版本验证失败，请尝试重新进行版本验证！
	TIP_DOWNLOAD_FILE_COMPLETE =		518,			//#%1!s! 下载完毕！
	ERR_DOWNLOAD_FILE2 =				519,			//#%1!s! 下载失败！
	ERR_COPY_FILE =						520,			//错误: 文件拷贝失败 - %1!s! >> %2!s!
	TIP_ALL_FILES_DOWNLOAD_COMPLETE =	521,			//#全部文件下载完毕！

	HTM_LOCAL_VERSION_1	=				601,			// 	本地版本:<span>%1!hu!.%2!hu!.%3!hu!</span>                   
	HTM_LOCAL_VERSION_2 =				602,			// 	本地客户端版本:<span>%1!hu!.%2!hu!.%3!hu!</span>             
	HTM_LOCAL_VERSION_3 =				603,			// 	本地客户端版本:<span>%1!hu!.%2!hu!.%3!hu! [最新]</span>      
	HTM_RELEASE_DATE_1 =				604,			// 	发布日期:<span>%1!u!月%2!u!日</span>                         
	HTM_RELEASE_DATE_2 =				605,			// 	发布日期:<span>%1!u!.%2!u!.%3!u!</span>                      
	HTM_RELEASE_DATE_3 =				606,			// 	发布日期:<span>%1!u!年%2!u!月%3!u!日</span>                  
	HTM_LATEST_VERSION =				607,			// 	最新版本:<span>%1!hu!.%2!hu!.%3!hu!</span>                   
	HTM_RELEASE_SN =					608,			// 	发布序号:<span>%1!hu!</span>                                 
	HTM_BAD_LOCAL_INSTALLATION =		609,			// 	<span>[存在问题，建议进行版本验证]</span>                    
	HTM_VERSION_INFO_FORMAT_0 =			620,			//	%1 %2  %3 %4                                                 
	HTM_VERSION_INFO_FORMAT_1 =			621,			//	%1%2%3%4                                                     
	HTM_VERSION_INFO_FORMAT_2 =			622,			//	%1   %2    %3                                                
	HTM_VERSION_INFO_FORMAT_3 =			623,			//	%1   %2    %3                                                
	HTM_VERSION_INFO_FORMAT_4 =			624,			//	%1   %2        

	TOK_BUTTON_OK					=	700,// 确定
	TOK_BUTTON_CANCEL				=	701,// 取消
	TOK_BUTTON_OPEN					=	702,// 打开
	TOK_BUTTON_CLOSE				=	703,// 关闭
	TOK_BUTTON_EXIT					=	704,// 退出
	TOK_BUTTON_SAVE					=	705,// 保存
	TOK_BUTTON_SAVE_AS				=	706,// 另存为...
	TOK_BUTTON_COPY					=	707,// 复制
	TOK_BUTTON_PASTE				=	708,// 粘贴
	TOK_BUTTON_SELECT_ALL			=	709,// 全选
	TOK_BUTTON_REVERT_SELECTION		=	710,// 反选
	TOK_BUTTON_HELP					=	720,// 帮助
	TOK_BUTTON_ABOUT				=	721,// 关于 %1!s! ...
	TOK_BUTTON_SHOW_S				=	731,// 显示窗口(&S)
	TOK_BUTTON_EXIT_X				=	732,// 退出(&X)

	TOK_BUTTON_CHECK_FILES			=	800,// 检查文件
	TOK_LABEL_RESET_CONFIG			=	801,// 重置《%1!s!》配置方案 (需要重新进行游戏设置及按键设置)
    TOK_LABEL_SELECT_UPDATE_SERVER	=	802,// 选择更新服务器：
    TOK_LABEL_START_CHECKING		=	803,// 开始检查文件...
    TOK_LABEL_CHECKING_FILES		=	804,// 正在检查文件...
};