
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include <set>
#include <map>
#include <list>
#include <vector>

// share include
#include "common/conf.h"
#include "common/log.h"
#include "common/thread.h"
#include "io/protocol.h"
#include "io/rpc.h"
#include "rpc/errcode.h"

// extern state
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State AuAnyClient;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State AuthClient;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State CrossClient;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State CrossServer;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State DeliverImport;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State DeliverService;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State GameDBServer;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State Null;
} 
} 

