// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate
// it is important that you use premake recreate this file if changing xml parsers or codecs for the static builds
#define CEGUI_HAS_FREETYPE 
#define CEGUI_HAS_DEFAULT_LOGGER 
#define CEGUI_HAS_PCRE_REGEX 
#define CEGUI_SAMPLES_USE_DIRECTX_9
#define CEGUI_DEFAULT_IMAGE_CODEC CEGUI_CODEC_cocos2d
#define CEGUI_LOAD_MODULE_DEBUG_SUFFIX "_d"
#define CEGUI_LOAD_MODULE_APPEND_SUFFIX_FOR_DEBUG 1
#define CEGUI_SAMPLES_USE_OPENGL 
#define CEGUI_FALAGARD_RENDERER 
//#define CEGUI_WITH_cocos2dxml 1
#ifdef FORCEGUIEDITOR
	#define CEGUI_WITH_xmlio   1
#else
	#define CEGUI_WITH_ljxml   1
#endif

#ifdef PUBLISHED_VERSION
	#ifdef FORCEGUIEDITOR
		#define CEGUI_DEFAULT_XMLPARSER CEGUI_WITH_xmlio
	#else
		#define CEGUI_DEFAULT_XMLPARSER CEGUI_WITH_ljxml
	#endif
#else   
    #define CEGUI_DEFAULT_XMLPARSER CEGUI_WITH_cocos2dxml
#endif
#define CEGUI_LUA_VER 51
#define CEGUI_CODEC_cocos2d 1
