
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 这个包含所有的协议
// 当把实现写在头文件中时，很容易产生循环。这时，不要使用这个文件。

#include "gnet/RemoteLog.hpp"
#include "gnet/RemoteLogVital.hpp"
#include "gnet/StatInfo.hpp"
#include "gnet/StatInfoVital.hpp"
