
// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include "rpcgen.hpp"
#include "protocols.hpp"

// include managers
#include "LogClientManager.hpp"
#include "LogClientTcpManager.hpp"

// protocol stubs
static gnet::RemoteLog gnet_RemoteLog((void*)0);
static gnet::RemoteLogVital gnet_RemoteLogVital((void*)0);
static gnet::StatInfo gnet_StatInfo((void*)0);
static gnet::StatInfoVital gnet_StatInfoVital((void*)0);

// state stubs
namespace gnet { 
namespace state { 
static GNET::Protocol::Type _LogNormal[] = {
	gnet::StatInfo::PROTOCOL_TYPE,
	gnet::StatInfoVital::PROTOCOL_TYPE,
	gnet::RemoteLog::PROTOCOL_TYPE,
	gnet::RemoteLogVital::PROTOCOL_TYPE,
};
GNET::Protocol::Manager::Session::State LogNormal(_LogNormal, sizeof(_LogNormal)/sizeof(GNET::Protocol::Type), 3600);

} 
} 
namespace gnet { 
namespace state { 
static GNET::Protocol::Type _LogNull[] = {
	0,
};
GNET::Protocol::Manager::Session::State LogNull(_LogNull, (size_t)0, 3600);

} 
} 

