
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include <set>
#include <map>
#include <list>
#include <vector>

// share include
#include "common/conf.h"
#include "common/log.h"
#include "common/thread.h"
#include "io/protocol.h"
#include "io/rpc.h"
#include "rpc/errcode.h"

// extern state
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State LogNormal;
} 
} 
namespace gnet { 
namespace state { 
extern GNET::Protocol::Manager::Session::State LogNull;
} 
} 

