APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -std=c++11
APP_ABI := armeabi-v7a
APP_PLATFORM := android-17
CFLAGS := -g

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1 -DXPP_IOS -DNDEBUG -DPUBLISHED_VERSION -DLOGCAT
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=0 -DXPP_IOS -DNDEBUG -DPUBLISHED_VERSION
  APP_OPTIM := release
endif

NDK_TOOLCHAIN_VERSION := 4.8