
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include <set>
#include <map>
#include <list>
#include <vector>

#include "win32/share.hpp"

namespace authc { 
void RegisterProtocols();
void UnregisterProtocols();
} 
