//////////////////////////////////////////////////////////////////////////
// File:		CEGUIPropertySerializer_v1.h
// Author:	Ñî´ºÀ×
// Date:		2016/02/29
//////////////////////////////////////////////////////////////////////////

#ifndef _CEGUIPropertySerializer_v1_h_
#define _CEGUIPropertySerializer_v1_h_

#include "../CEGUIPropertySerializer.h"

namespace CEGUI
{
	namespace BinLayout
	{
		PROPERTY_SERIALIZER_CLASS_DECL(ImageSetName, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ImageName, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(TotalFrame, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(AnimationSpeed, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Selected, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ReadOnly, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ValidationString, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(CaratIndex, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(EditSelectionStart, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(EditSelectionLength, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(MaxEditTextLength, 1, getMaxTextLength, setMaxTextLength);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(SortList, 1, isSortEnabled, setSortingEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(ForceVertScrollbar, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ForceHorzScrollbar, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(SingleClickMode, 1, getSingleClickEnabled, setSingleClickEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(DraggingEnabled, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(DragAlpha, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DragThreshold, 1, getPixelDragThreshold, setPixelDragThreshold);
		PROPERTY_SERIALIZER_CLASS_DECL(DragCursorImage, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(StickyMode, 1, isStickyModeEnabled, setStickyModeEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_s(FixedDragOffset, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UseFixedDragOffset, 1, isUsingFixedDragOffset, setUsingFixedDragOffset);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(MaskText, 1, isTextMasked, setTextMasked);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(MaskCodepoint, 1, getMaskCodePoint, setMaskCodePoint);
		PROPERTY_SERIALIZER_CLASS_DECL(SelectionStart, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SelectionLength, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MaxTextLength, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(NormalTextColour, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SelectedTextColour, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ActiveSelectionColour, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(InactiveSelectionColour, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BackGroundEnable, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(SupportTabKey, 1, isSuppotTabKey, EnableSuppotTabKey);
		TPL_PROPERTY_SERIALIZER_CLASS_b(TabOrderID, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(SizingEnabled, 1, isSizingEnabled, setSizingEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(FrameEnabled, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(TitlebarEnabled, 1, isTitleBarEnabled, setTitleBarEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(CloseButtonEnabled, 1, isCloseButtonEnabled, setCloseButtonEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(RollUpEnabled, 1, isRollupEnabled, setRollupEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(RollUpState, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DragMovingEnabled, 1, isDragMovingEnabled, setDragMovingEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_s(SizingBorderThickness, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(NSSizingCursorImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(EWSizingCursorImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(NWSESizingCursorImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(NESWSizingCursorImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(GroupID, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(StateImageExtendID, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ItemCellStyle, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Selectable, 1, isSelectable, setSelectable);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AutoResizeEnabled, 1, isAutoResizeEnabled, setAutoResizeEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(SortEnabled, 1, isSortEnabled, setSortEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(SortMode, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MultiSelect, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(RowCount, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(ColCount, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(CellWidth, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(CellHeight, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(SpaceX, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(SpaceY, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(StartX, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(StartY, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(UserID, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Sort, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ItemTooltips, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ColumnsSizable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ColumnsMovable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SortSettingEnabled, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SortDirection, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SortColumnID, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Sizable, 1, isSizingEnabled, setSizingEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Clickable, 1, isClickable, setClickable);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Dragable, 1, isDragMovingEnabled, setDragMovingEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(SizingCursorImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MovingCursorImage, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(ItemSpacing, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AllowMultiplePopups, 1, isMultiplePopupsAllowed, setAllowMultiplePopups);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(NominatedSelectionColumnID, 1, getNominatedSelectionColumnID, setNominatedSelectionColumn);
		TPL_PROPERTY_SERIALIZER_CLASS_s(NominatedSelectionRow, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SelectionMode, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ColumnHeader, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(WordWrap, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SelectionBrushImage, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(FadeInTime, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(FadeOutTime, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(CurrentProgress, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(FrameEnable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(StepSize, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SizeType, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(LineSpace, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(TopAfterLoadFont, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ContentPaneAutoSized, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ContentArea, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(HorzStepSize, 1, getHorizontalStepSize, setHorizontalStepSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(HorzOverlapSize, 1, getHorizontalOverlapSize, setHorizontalOverlapSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(HorzScrollPosition, 1, getHorizontalScrollPosition, setHorizontalScrollPosition);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(VertStepSize, 1, getVerticalStepSize, setVerticalStepSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(VertOverlapSize, 1, getVerticalOverlapSize, setVerticalOverlapSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(VertScrollPosition, 1, getVerticalScrollPosition, setVerticalScrollPosition);
		TPL_PROPERTY_SERIALIZER_CLASS_s(PaneScrollMode, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(DocumentSize, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(PageSize, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(OverlapSize, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(ScrollPosition, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ChildExtentsArea, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(CurrentValue, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MaximumValue, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(ClickStepSize, 1, getClickStep, setClickStep);
		TPL_PROPERTY_SERIALIZER_CLASS_s(MinimumValue, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(TextInputMode, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Status, 1, getStatusString, setStatus);
		TPL_PROPERTY_SERIALIZER_CLASS_s(TabHeight, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(TabTextPadding, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(TabPanePosition, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(TabSeparation, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(TabFirstInterval, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(HotTracked, 1, isHotTracked, setHotTracked);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(VertFree, 1, isVertFree, setVertFree);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(HorzFree, 1, isHorzFree, setHorzFree);
		PROPERTY_SERIALIZER_CLASS_DECL(VertRange, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(HorzRange, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(HoverTime, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(DisplayTime, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(FadeTime, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MaskImage, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(PropertyDefinition, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BlinkCaret, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BlinkCaretTimeout, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(SegmentWidgetType, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VerticalProgress, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ReversedProgress, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VerticalScrollbar, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VerticalSlider, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ReversedDirection, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Image, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ImageSizeEnable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BackgroundEnabled, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(TextColours, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(HorzFormatting, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VertFormatting, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VertScrollbar, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(HorzScrollbar, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(HorzExtent, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(VertExtent, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BorderEnable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(BorderColour, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(DefaultColourEnable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(DefaultBorderEnable, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Title, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(TabButtonType, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(ID, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(Alpha, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Font, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(Text, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(MouseCursorImage, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(ClippedByParent, 1, isClippedByParent, setClippedByParent);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(InheritsAlpha, 1, inheritsAlpha, setInheritsAlpha);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AlwaysOnTop, 1, isAlwaysOnTop, setAlwaysOnTop);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(TopMost, 1, isTopMost, setTopMost);
		PROPERTY_SERIALIZER_CLASS_DECL(Disabled, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Visible, 1, isVisible, setVisible);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(RestoreOldCapture, 1, restoresOldCapture, setRestoreCapture);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DestroyedByParent, 1, isDestroyedByParent, setDestroyedByParent);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(ZOrderChangeEnabled, 1, isZOrderingEnabled, setZOrderingEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(WantsMultiClickEvents, 1, wantsMultiClickEvents, setWantsMultiClickEvents);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(MouseButtonDownAutoRepeat, 1, isMouseAutoRepeatEnabled, setMouseAutoRepeatEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_s(AutoRepeatDelay, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_s(AutoRepeatRate, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DistributeCapturedInputs, 1, distributesCapturedInputs, setDistributesCapturedInputs);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(CustomTooltipType, 1, getTooltipType, setTooltipType);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Tooltip, 1, getTooltipText, setTooltipText);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(InheritsTooltipText, 1, inheritsTooltipText, setInheritsTooltipText);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(RiseOnClick, 1, isRiseOnClickEnabled, setRiseOnClickEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(VerticalAlignment, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(HorizontalAlignment, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedAreaRect, 1, getArea, setArea);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedPosition, 1, getPosition, setPosition);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedXPosition, 1, getXPosition, setXPosition);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedYPosition, 1, getYPosition, setYPosition);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedSize, 1, getSize, setSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedWidth, 1, getWidth, setWidth);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedHeight, 1, getHeight, setHeight);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedMinSize, 1, getMinSize, setMinSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(UnifiedMaxSize, 1, getMaxSize, setMaxSize);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(MousePassThroughEnabled, 1, isMousePassThroughEnabled, setMousePassThroughEnabled);
		PROPERTY_SERIALIZER_CLASS_DECL(WindowRenderer, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(LookNFeel, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DragDropTarget, 1, isDragDropTarget, setDragDropTarget);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AutoRenderingSurface, 1, isUsingAutoRenderingSurface, setUsingAutoRenderingSurface);
		PROPERTY_SERIALIZER_CLASS_DECL(Scale, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Rotation, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(XRotation, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(YRotation, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(ZRotation, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(NonClient, 1, isNonClientWindow, setNonClientWindow);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(TextParsingEnabled, 1, isTextParsingEnabled, setTextParsingEnabled);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DisplaySizeChangePosEnabled, 1, GetDisplaySizeChangePosEnable, SetDisplaySizeChangePosEnable);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(WindowDieTime, 1, getDieTime, setDieTime);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(DragMoveEnable, 1, isHandleDragMove, SetHandleDragMove);
		PROPERTY_SERIALIZER_CLASS_DECL(XPos, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(YPos, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Width, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Height, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(EnableSound, 1, isSoundEable, SetSoundEnable);
		TPL_PROPERTY_SERIALIZER_CLASS_b(SoundResource, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(CloseSoundResource, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(LimitWindowSize, 1, getLimitSize, setLimitSize);
		PROPERTY_SERIALIZER_CLASS_DECL(CreateEffectType, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(CloseEffectType, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(AllowModalStateClick, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AllowShowWithModalState, 1, isAllowShowWithModalState, EnabledAllowShowWithModalState);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(ModalState, 1, isModalAfterShow, EnableModalStateAfterShow);
		TPL_PROPERTY_SERIALIZER_CLASS_b(CloseIsHide, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_b(IsPixelDecide, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(LuaClass, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(LuaMemberName, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(LuaEventOnClicked, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(NativeRes, 1, getNativeResolution, setNativeResolution);
		PROPERTY_SERIALIZER_CLASS_DECL(Name, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(AutoScaled, 1, isAutoScaled, setAutoScaled);
		TPL_PROPERTY_SERIALIZER_CLASS_s(PointSize, 1);
		TPL_PROPERTY_SERIALIZER_CLASS_GS(Antialiased, 1, isAntiAliased, setAntiAliased);
		TPL_PROPERTY_SERIALIZER_CLASS_s(Imageset, 1);
		PROPERTY_SERIALIZER_CLASS_DECL(Mapping, 1);
	}
}

#endif