//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SoundEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_SoundEditorTYPE             129
#define IDD_MAIN_DLG                    130
#define IDD_TAB_PROP_PANEL              131
#define IDD_TEST_PANEL                  132
#define IDD_ENV_PANEL                   133
#define IDR_TOOLBAR_EDITOR              134
#define IDR_PNG_AREA                    135
#define IDD_MINIMAP_PANEL               136
#define IDD_BKG_PANEL                   137
#define IDD_SOUND_LIST                  138
#define IDD_STEP_PANEL                  139
#define IDD_2INPUTS_DIALOG              140
#define IDD_MAZE_SETTING_DLG            141
#define IDD_SOUND_RESOURCE              142
#define IDD_BKGVOL_PANEL                143
#define IDC_PROP_TAB                    1000
#define IDC_CHECK_DRAW_ENV_AREA         1001
#define IDC_CHECK_DRAW_BKG_AREA         1002
#define IDC_SOUND_LIST                  1004
#define IDC_ADD_SOUND                   1005
#define IDC_DEL_SOUND                   1006
#define IDC_SLIDER_MAX_V                1007
#define IDC_SLIDER_MIN_V                1008
#define IDC_SLIDER_MAX_F                1009
#define IDC_SLIDER_MIN_F                1010
#define IDC_EDIT_MAX_V                  1011
#define IDC_EDIT_MIN_V                  1012
#define IDC_EDIT_MAX_F                  1013
#define IDC_EDIT_MIN_F                  1014
#define IDC_EDIT_L                      1015
#define IDC_EDIT_MIN_INTERVAL           1016
#define IDC_COMBO_TYPE                  1017
#define IDC_BUTTON_ADD_TYPE             1018
#define IDC_BUTTON_DEL_TYPE             1019
#define IDC_STATIC_MAX_V                1020
#define IDC_RADIO_POLYGON_NONE          1021
#define IDC_RADIO_POLYGON_BASE          1022
#define IDC_RADIO_POLYGON_CUT           1023
#define IDC_BUTTON_DELETE_CUTS          1024
#define IDC_SLIDER_SCALE                1025
#define IDC_NAME                        1026
#define IDC_BUTTON_UP                   1027
#define IDC_BUTTON_DOWN                 1028
#define IDC_STATIC_VOL                  1029
#define IDC_SLIDER_VOL                  1030
#define IDC_EDIT_VOL                    1031
#define IDC_CHECK_DARK                  1032
#define IDC_SLIDER_CYCLE                1033
#define IDC_SLIDER_TIME                 1034
#define IDC_LAB_TIME                    1035
#define IDC_ALL_SOUND_LIST              1036
#define IDC_EDIT_PRIORITY               1037
#define IDC_EDIT_MAX_INTERVAL           1038
#define IDC_COMBO_SOUND_TYPE            1039
#define IDC_CHECK_LOOPING               1040
#define IDC_EDIT_BEGIN_TIME             1041
#define IDC_EDIT_END_TIME               1042
#define IDC_EDIT_FADE_IN_TIME           1043
#define IDC_EDIT_FADE_OUT_TIME          1044
#define IDC_GROUND_TYPE_LIST            1045
#define IDC_COMBO_BRUSH_SIZE            1046
#define IDC_GROUP_GROUND_TYPE           1047
#define IDC_STATIC_BRUSH_SIZE           1048
#define IDC_GROUP_ACTOR_TYPE            1049
#define IDC_LIST_ACTOR_TYPE             1050
#define IDC_BUTTON_ADD_ACTOR            1051
#define IDC_BUTTON_DEL_ACTOR            1052
#define IDC_BUTTON_RESET_SEL_ACT        1054
#define IDC_BUTTON_RESET_ALL_ACT_TYPE   1055
#define IDC_CHECK_ENV                   1056
#define IDC_SLIDER_ENV                  1057
#define IDC_CHECK_BKG                   1058
#define IDC_SLIDER_BKG                  1059
#define IDC_COMBO_MODEL                 1060
#define IDC_COMBO_LAYER                 1061
#define IDC_COMBO_COMPONENT             1062
#define IDC_COMBO_ACT_TYPE              1063
#define IDC_BUTTON_SAVE                 1064
#define IDC_GROUP                       1065
#define IDC_COMBO_ACTION_TYPE           1066
#define IDC_COMBO_ACTION_NAME           1067
#define IDC_BUTTON_SAVE_AS_DEFAULT      1068
#define IDC_COMBO_RIDE_TYPE             1069
#define IDC_EDIT1                       1070
#define IDC_EDIT2                       1071
#define IDC_STATIC_INFO                 1072
#define IDC_STATIC_TEXT1                1073
#define IDC_STATIC_TEXT2                1074
#define IDC_LIST_NOTIFY                 1075
#define IDC_COMBO_NOTIFY_ACTION_NAME    1076
#define IDC_COMBO_NOTIFY_ACTION_FRAME   1077
#define IDC_EDIT_MAZE_URL_FORMAT        1078
#define IDC_LIST_MAP_ID                 1079
#define IDC_LIST_MAZE_COLOR             1080
#define IDC_EDIT_SPRITE_MASK            1081
#define IDC_BUTTON_ADD_MAPID            1082
#define IDC_BUTTON_DEL_MAPID            1083
#define IDC_BUTTON_ADD_MASK_COLOR       1084
#define IDC_BUTTON_DEL_MASK_COLOR       1085
#define IDC_SLIDER_ALPHA                1086
#define IDC_CHECK_DRAW_STEP             1087
#define IDC_LIST_RES                    1088
#define IDC_COUNT_REF                   1089
#define IDC_REFRESH                     1090
#define IDC_DELETE                      1091
#define IDC_EXPORT_TO_EXCEL             1092
#define IDC_CHECK1                      1093
#define IDC_COMBO_PLAY_MODE             1094
#define IDC_PLAY_MODE_STATIC            1095
#define IDC_STATIC_FADE_IN              1096
#define IDC_STATIC_FADE_OUT             1097
#define IDC_CHECK_DRAW_BKG_VOL          1098
#define ID_TOOL_MOVE                    32773
#define ID_TOOL_SELECT                  32774
#define ID_TOOL_POLYGON                 32775
#define ID_TOOL_CIRCLE                  32776
#define ID_DRAW_GIRD                    32777
#define ID_MAZE_INFO                    32778
#define ID_DRAW_MAZE                    32779
#define ID_32780                        32780
#define ID_ALL_RES                      32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
