$axure.loadCurrentPage({
  "url":"组队界面（有队伍）.html",
  "generationDate":new Date(1429602386605.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"d623ce73d5bc40feabe8b39c66ee10a3",
    "type":"Axure:Page",
    "name":"组队界面（有队伍）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"21ac68f4d7e94a5c8e1ed59e1f449740",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62394e9f28a243d9a77ada2ff94c2071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"f1e33006635a49b1907bad2b59517640",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd174bccb974fcb93b24a7a07cbe6cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"7c44d1e4d2494f60908dd3be9cfafe45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6546a1960987408b9469d5d78df6c447",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"5a09dd0a0b3e40399a3a94e26bea9406",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044c92f8c639435b9b9f02f28c0561b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"108275b189b443af9645a012913bbf6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84c42fdae3a64a9ba2bbf024a3dcd895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"5cbb34136a21461fa3952eece8ee7fcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e070bb572e64584a845420081ee33bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u10.png"}},
{
          "id":"c629dd699d49478eaa29f6f441a29a9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7b09e29f03b465aa2f6814d5de3063d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"7b911cc1e60f4c5b8a59e38ac80c37d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d03e31bce1429e8a37e5f16376fc62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"1f9c136d70464664888342dcd726a273",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":280},
            "size":{
              "width":216,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6e30afd0e548ca8d984a0ff91dcfea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":280},
                "size":{
                  "width":216,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"e5156078df5a481a9b3e5fa69b77151e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":240},
            "size":{
              "width":109,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"735cf0ed18a04ae8adff1643eb37d9f4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":240},
            "size":{
              "width":105,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组队界面（无队伍）",
                      "target":{
                        "targetType":"page",
                        "url":"组队界面（无队伍）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e80fa7d57dd84a99a3bd63a3aa4c850c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5856a61651ee4965b5f2881e2934ebf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"6078a663ba27450c895686a736d6fff9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6fabf6b5e1d4ce8bda1b1691e986545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"4df49ecf1f9c4534a4b7f954f26835eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56326a7b602b4e38a91d678267320032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"b85399aab5e342febf69d5e2d42ecd31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c53b46c66fe48cabdd42bd1f9d4dddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":250},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"35fd92dea7ec45e99d40a71a9ac8c6ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0fef2f940484093bf2732bbda3443f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"f7fb806135e644708b4ea323332fa768",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba31119a61d14b16a8aaa378700354cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"0ed00e986be9404aa5d3a5447e044ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1445c6d451b44d8835e702bc78a70a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"54c1fc691c494200a7750d4522593dbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd214cd2429e4e0690b588d57639a7b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"d1916f19a1c3498dbd07e8cd1aea2621",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":558},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b9a766583024906951539538ec76976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":558},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 背包功能",
                      "target":{
                        "targetType":"page",
                        "url":"背包功能.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"1ada8f2d664e4a94af04762586b4f6df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b97959093f49efa3fd4b502af55298",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"db5134873bda4043bad062cfb9927441",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c68d40383f41169c08d45796a66607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"28c8a28f4e0a4ba5bbb357b9e46ec1ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed70f66dd5694e29a2c8b4c51e139526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"6ee2ff14717a46e88836c1d25641df13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":136},
            "size":{
              "width":115,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287a8ae333614602af6ac81e5b54ea2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":136},
                "size":{
                  "width":115,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u44.png"}},
{
          "id":"5e25e7171da44de59983329614ef5d1c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6fb1752fa388447e8d0906b09341def6",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":570},
            "size":{
              "width":328,
              "height":168}},
          "adaptiveStyles":{
}},
{
          "id":"b431c80c5d8a447fbfc0b64bce4d17a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bbcf264d9f41fdb0e986c23e5369fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"687c8b5afa73412c93c816db2b92c76b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc1ac314ef5640a7a90ea066ad7858e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"4f3455e9fa9e4e5d93342c60abb2c302",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e3a423e49464cc0a4b7c24ccdede4c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"35789e2b541d4d1f91301210a711b0e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d0d109bcbfe48d48eeafa1f53049c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"f35e0271fe814498b04b6bf3208793b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b700ba26e104505881a5ad0ee217246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"a306b4fd647641c4b5fdf797ca144cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":171},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81b8dd4bdcaa4d9f941983f63c5af9a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":171},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图界面",
                      "target":{
                        "targetType":"page",
                        "url":"地图界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"48b5af7fbe7e43fcaa311f7b936d81fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":111},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26968cd3e1694443a5fa99f5632047c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":111},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"9102fdb9b6d9462a8623187e958edfe1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":280},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"052974f66eb14f628634c1836dd3d3b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":280},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"dce3d8ad491e4221bb32ca328e0143c3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":320},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261feee1681d408591f0fb22d352f83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":320},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"dae115e61f9a4b5293e635c29562d3dc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":360},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ca42d58cc64522810c90033d2da9c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":360},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"7969e6833b3d4f1e8f7a9149b5797b34",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":400},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d0ed6b2c769488398ebb69b476eba96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":400},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"d2e9dd2b9fd74c5eb3fa12318784e40b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":440},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95299c967fe46df87ff6bfae014b278",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":440},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"fd40efd96279400bbe543b6c02a5e5ac",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":1156,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3ec75dd5864d70bea778f7de78a2ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":1156,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 功能缩放",
                      "target":{
                        "targetType":"page",
                        "url":"功能缩放.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "21ac68f4d7e94a5c8e1ed59e1f449740":{
      "scriptId":"u0"},
    "62394e9f28a243d9a77ada2ff94c2071":{
      "scriptId":"u1"},
    "f1e33006635a49b1907bad2b59517640":{
      "scriptId":"u2"},
    "2cd174bccb974fcb93b24a7a07cbe6cd":{
      "scriptId":"u3"},
    "7c44d1e4d2494f60908dd3be9cfafe45":{
      "scriptId":"u4"},
    "6546a1960987408b9469d5d78df6c447":{
      "scriptId":"u5"},
    "5a09dd0a0b3e40399a3a94e26bea9406":{
      "scriptId":"u6"},
    "044c92f8c639435b9b9f02f28c0561b9":{
      "scriptId":"u7"},
    "108275b189b443af9645a012913bbf6c":{
      "scriptId":"u8"},
    "84c42fdae3a64a9ba2bbf024a3dcd895":{
      "scriptId":"u9"},
    "5cbb34136a21461fa3952eece8ee7fcc":{
      "scriptId":"u10"},
    "3e070bb572e64584a845420081ee33bb":{
      "scriptId":"u11"},
    "c629dd699d49478eaa29f6f441a29a9b":{
      "scriptId":"u12"},
    "b7b09e29f03b465aa2f6814d5de3063d":{
      "scriptId":"u13"},
    "7b911cc1e60f4c5b8a59e38ac80c37d8":{
      "scriptId":"u14"},
    "24d03e31bce1429e8a37e5f16376fc62":{
      "scriptId":"u15"},
    "1f9c136d70464664888342dcd726a273":{
      "scriptId":"u16"},
    "ce6e30afd0e548ca8d984a0ff91dcfea":{
      "scriptId":"u17"},
    "e5156078df5a481a9b3e5fa69b77151e":{
      "scriptId":"u18"},
    "735cf0ed18a04ae8adff1643eb37d9f4":{
      "scriptId":"u19"},
    "e80fa7d57dd84a99a3bd63a3aa4c850c":{
      "scriptId":"u20"},
    "5856a61651ee4965b5f2881e2934ebf8":{
      "scriptId":"u21"},
    "6078a663ba27450c895686a736d6fff9":{
      "scriptId":"u22"},
    "d6fabf6b5e1d4ce8bda1b1691e986545":{
      "scriptId":"u23"},
    "4df49ecf1f9c4534a4b7f954f26835eb":{
      "scriptId":"u24"},
    "56326a7b602b4e38a91d678267320032":{
      "scriptId":"u25"},
    "b85399aab5e342febf69d5e2d42ecd31":{
      "scriptId":"u26"},
    "2c53b46c66fe48cabdd42bd1f9d4dddf":{
      "scriptId":"u27"},
    "35fd92dea7ec45e99d40a71a9ac8c6ed":{
      "scriptId":"u28"},
    "b0fef2f940484093bf2732bbda3443f9":{
      "scriptId":"u29"},
    "f7fb806135e644708b4ea323332fa768":{
      "scriptId":"u30"},
    "ba31119a61d14b16a8aaa378700354cd":{
      "scriptId":"u31"},
    "0ed00e986be9404aa5d3a5447e044ccb":{
      "scriptId":"u32"},
    "d1445c6d451b44d8835e702bc78a70a3":{
      "scriptId":"u33"},
    "54c1fc691c494200a7750d4522593dbe":{
      "scriptId":"u34"},
    "dd214cd2429e4e0690b588d57639a7b3":{
      "scriptId":"u35"},
    "d1916f19a1c3498dbd07e8cd1aea2621":{
      "scriptId":"u36"},
    "3b9a766583024906951539538ec76976":{
      "scriptId":"u37"},
    "1ada8f2d664e4a94af04762586b4f6df":{
      "scriptId":"u38"},
    "a5b97959093f49efa3fd4b502af55298":{
      "scriptId":"u39"},
    "db5134873bda4043bad062cfb9927441":{
      "scriptId":"u40"},
    "33c68d40383f41169c08d45796a66607":{
      "scriptId":"u41"},
    "28c8a28f4e0a4ba5bbb357b9e46ec1ae":{
      "scriptId":"u42"},
    "ed70f66dd5694e29a2c8b4c51e139526":{
      "scriptId":"u43"},
    "6ee2ff14717a46e88836c1d25641df13":{
      "scriptId":"u44"},
    "287a8ae333614602af6ac81e5b54ea2b":{
      "scriptId":"u45"},
    "5e25e7171da44de59983329614ef5d1c":{
      "scriptId":"u46"},
    "6fb1752fa388447e8d0906b09341def6":{
      "scriptId":"u47"},
    "b431c80c5d8a447fbfc0b64bce4d17a8":{
      "scriptId":"u48"},
    "47bbcf264d9f41fdb0e986c23e5369fa":{
      "scriptId":"u49"},
    "687c8b5afa73412c93c816db2b92c76b":{
      "scriptId":"u50"},
    "fc1ac314ef5640a7a90ea066ad7858e3":{
      "scriptId":"u51"},
    "4f3455e9fa9e4e5d93342c60abb2c302":{
      "scriptId":"u52"},
    "0e3a423e49464cc0a4b7c24ccdede4c2":{
      "scriptId":"u53"},
    "35789e2b541d4d1f91301210a711b0e2":{
      "scriptId":"u54"},
    "3d0d109bcbfe48d48eeafa1f53049c0c":{
      "scriptId":"u55"},
    "f35e0271fe814498b04b6bf3208793b2":{
      "scriptId":"u56"},
    "9b700ba26e104505881a5ad0ee217246":{
      "scriptId":"u57"},
    "a306b4fd647641c4b5fdf797ca144cab":{
      "scriptId":"u58"},
    "81b8dd4bdcaa4d9f941983f63c5af9a6":{
      "scriptId":"u59"},
    "48b5af7fbe7e43fcaa311f7b936d81fe":{
      "scriptId":"u60"},
    "26968cd3e1694443a5fa99f5632047c2":{
      "scriptId":"u61"},
    "9102fdb9b6d9462a8623187e958edfe1":{
      "scriptId":"u62"},
    "052974f66eb14f628634c1836dd3d3b1":{
      "scriptId":"u63"},
    "dce3d8ad491e4221bb32ca328e0143c3":{
      "scriptId":"u64"},
    "261feee1681d408591f0fb22d352f83d":{
      "scriptId":"u65"},
    "dae115e61f9a4b5293e635c29562d3dc":{
      "scriptId":"u66"},
    "81ca42d58cc64522810c90033d2da9c7":{
      "scriptId":"u67"},
    "7969e6833b3d4f1e8f7a9149b5797b34":{
      "scriptId":"u68"},
    "2d0ed6b2c769488398ebb69b476eba96":{
      "scriptId":"u69"},
    "d2e9dd2b9fd74c5eb3fa12318784e40b":{
      "scriptId":"u70"},
    "a95299c967fe46df87ff6bfae014b278":{
      "scriptId":"u71"},
    "fd40efd96279400bbe543b6c02a5e5ac":{
      "scriptId":"u72"},
    "de3ec75dd5864d70bea778f7de78a2ed":{
      "scriptId":"u73"}}});