$axure.loadCurrentPage({
  "url":"战斗功能按钮.html",
  "generationDate":new Date(1429602387912.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"7ef9964ff0f246f3a17f380bc11a1d1f",
    "type":"Axure:Page",
    "name":"战斗功能按钮",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91d53042d91b43be8f6170acd7e40346",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ce0084cd0c412790ded65af9cbbfa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"1c44146ab4864b798a036bb6c9b0ff52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a05c6a571fc74f45994089a824f587be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"d4e6520b8fe643cc900229be60d18931",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4372af704aa487aa191e9bc79c72189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"8214b49d48ef4995b0a6da1253e0bf84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c312ca48ade24b0a91a626d08462e305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"b881e5f2646c4158a5a6e270cf6c996d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be2f63c5610412b80ad4a0461149259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"e6275720ec544b7dae66b07f969ccdb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb00549d2d9466cbd50ac332093f25f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"a67373cfef784e3fab2e142d448c8f5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198ff0804c5841689e35ec7a37f85bd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"dc7857041dcf413a88f7406793f48108",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a36b2bf6c314948b3fc81f468c6c73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"e9465b3b7a3748d39c73d2229a8c8a5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db24195d4b848e79ef1ae42fc8bba72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"f5628b4ac7d04f9eb2868b9999b21839",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4342b408f3040a897fd5a3f67381e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"00bcca1cab924c5185e49c0e238f3071",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9f7e2ca27d842aa9e1c79efb222d406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"953d7bd2736e4ac5bf433ff953edda72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24988ed7cb6a42dbb8ea3050504c1755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"5563f52143c541a39d4cb2d1f1d84861",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f77d5b1aafb742cd9dab283209f920f0",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":530},
            "size":{
              "width":328,
              "height":208}},
          "adaptiveStyles":{
}},
{
          "id":"feda581586c84d25ae242da0e023d630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":500},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e2d1d109c74cae86d12bc9a02a3e93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":500},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"88f2d446ff9e48b5bb9a17038d3c7bc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":500},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5da649f1b3a46ada30c2bce8770c7d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":500},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"a137e6ca709843629fbea22738bff09b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":500},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5974ec77bd1f4451a183c412230245b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":500},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"4d36d7111c0f44ada4fbb649ccd37a8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":500},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a2704d420394c38aa3570e27969d219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":500},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"a02ed8ee0b9442f3b3fc0c10cf0e0e6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12e277fb99c44da9a58cd683ab8fe857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"3f4f7cfc450e4b8780ab908585c4c9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a981f4e0467443dfb3439fd2b8bc0bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"971403d13c1949399597d9116383d707",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗布局",
                      "target":{
                        "targetType":"page",
                        "url":"战斗布局.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b2023c135a914980861ad7c844cc49bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":135},
            "size":{
              "width":115,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8e8cb1f80374bae82e012a2394a6612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":135},
                "size":{
                  "width":115,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u39.png"}},
{
          "id":"e1ca978c8f524113bc178ac647226893",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":115,
              "y":135},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4026a585beca4c2d9d648dec8d5dc768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":115,
                  "y":135},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"7fa8e00bdf284431bb2bd2502e2f3135",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":150,
              "y":135},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2a7f39625be4085b36cc1b87a6d28bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":150,
                  "y":135},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"3adf2c3e2cda4f4c9c0e5ef139ae07ee",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":185,
              "y":135},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f79e323ea949778d50fb9a51987e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":185,
                  "y":135},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"a090043a91b24458b4b4de1188805ef3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":115,
              "y":172},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"345ad4fc642d4788a981ed8b90747e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":115,
                  "y":172},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"fa8598271257410398f962f7ea9b1ce8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":150,
              "y":172},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73dcf82b85a3490aa99deadf5f1f49d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":150,
                  "y":172},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"17c8fd0d9346459ea18a6ed4b26679cc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":185,
              "y":172},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a710ce354f5d40ccad42df475dae14e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":185,
                  "y":172},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"b826e2058e80403fae6ae5ad26945e3e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":115,
              "y":210},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9472209a2bb424ba6a9fe721af43b12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":115,
                  "y":210},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"7fe85b584ce742dd8618d82809c7cf33",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":150,
              "y":210},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"836aa7f944e14118a4736fbb59c429b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":150,
                  "y":210},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"b8fb2ee2600441d38f4fc2e18a69f291",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":185,
              "y":210},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66cd91d9053b4fb29ec6ac9aafe69e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":185,
                  "y":210},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u41.png"}},
{
          "id":"1d767b0398fa43b18f09d581f02e34f0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":114},
            "size":{
              "width":128,
              "height":43}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"24b00cd96e1d4740bbd43ed914bafbdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":110,
              "y":535},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e696b8d2eaf545a9948adfe63642ab8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":110,
                  "y":535},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗功能按钮/u60.png"}},
{
          "id":"188a85e9b3574c4aabbe8e2605d9d705",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":530},
            "size":{
              "width":38,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754c07cfd8a547bb99cf4e0f892a2735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":530},
                "size":{
                  "width":38,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天放大/u72.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "91d53042d91b43be8f6170acd7e40346":{
      "scriptId":"u0"},
    "57ce0084cd0c412790ded65af9cbbfa0":{
      "scriptId":"u1"},
    "1c44146ab4864b798a036bb6c9b0ff52":{
      "scriptId":"u2"},
    "a05c6a571fc74f45994089a824f587be":{
      "scriptId":"u3"},
    "d4e6520b8fe643cc900229be60d18931":{
      "scriptId":"u4"},
    "f4372af704aa487aa191e9bc79c72189":{
      "scriptId":"u5"},
    "8214b49d48ef4995b0a6da1253e0bf84":{
      "scriptId":"u6"},
    "c312ca48ade24b0a91a626d08462e305":{
      "scriptId":"u7"},
    "b881e5f2646c4158a5a6e270cf6c996d":{
      "scriptId":"u8"},
    "0be2f63c5610412b80ad4a0461149259":{
      "scriptId":"u9"},
    "e6275720ec544b7dae66b07f969ccdb4":{
      "scriptId":"u10"},
    "7fb00549d2d9466cbd50ac332093f25f":{
      "scriptId":"u11"},
    "a67373cfef784e3fab2e142d448c8f5a":{
      "scriptId":"u12"},
    "198ff0804c5841689e35ec7a37f85bd1":{
      "scriptId":"u13"},
    "dc7857041dcf413a88f7406793f48108":{
      "scriptId":"u14"},
    "3a36b2bf6c314948b3fc81f468c6c73d":{
      "scriptId":"u15"},
    "e9465b3b7a3748d39c73d2229a8c8a5c":{
      "scriptId":"u16"},
    "7db24195d4b848e79ef1ae42fc8bba72":{
      "scriptId":"u17"},
    "f5628b4ac7d04f9eb2868b9999b21839":{
      "scriptId":"u18"},
    "f4342b408f3040a897fd5a3f67381e26":{
      "scriptId":"u19"},
    "00bcca1cab924c5185e49c0e238f3071":{
      "scriptId":"u20"},
    "b9f7e2ca27d842aa9e1c79efb222d406":{
      "scriptId":"u21"},
    "953d7bd2736e4ac5bf433ff953edda72":{
      "scriptId":"u22"},
    "24988ed7cb6a42dbb8ea3050504c1755":{
      "scriptId":"u23"},
    "5563f52143c541a39d4cb2d1f1d84861":{
      "scriptId":"u24"},
    "f77d5b1aafb742cd9dab283209f920f0":{
      "scriptId":"u25"},
    "feda581586c84d25ae242da0e023d630":{
      "scriptId":"u26"},
    "c7e2d1d109c74cae86d12bc9a02a3e93":{
      "scriptId":"u27"},
    "88f2d446ff9e48b5bb9a17038d3c7bc6":{
      "scriptId":"u28"},
    "b5da649f1b3a46ada30c2bce8770c7d6":{
      "scriptId":"u29"},
    "a137e6ca709843629fbea22738bff09b":{
      "scriptId":"u30"},
    "5974ec77bd1f4451a183c412230245b8":{
      "scriptId":"u31"},
    "4d36d7111c0f44ada4fbb649ccd37a8e":{
      "scriptId":"u32"},
    "1a2704d420394c38aa3570e27969d219":{
      "scriptId":"u33"},
    "a02ed8ee0b9442f3b3fc0c10cf0e0e6e":{
      "scriptId":"u34"},
    "12e277fb99c44da9a58cd683ab8fe857":{
      "scriptId":"u35"},
    "3f4f7cfc450e4b8780ab908585c4c9e3":{
      "scriptId":"u36"},
    "a981f4e0467443dfb3439fd2b8bc0bdf":{
      "scriptId":"u37"},
    "971403d13c1949399597d9116383d707":{
      "scriptId":"u38"},
    "b2023c135a914980861ad7c844cc49bd":{
      "scriptId":"u39"},
    "f8e8cb1f80374bae82e012a2394a6612":{
      "scriptId":"u40"},
    "e1ca978c8f524113bc178ac647226893":{
      "scriptId":"u41"},
    "4026a585beca4c2d9d648dec8d5dc768":{
      "scriptId":"u42"},
    "7fa8e00bdf284431bb2bd2502e2f3135":{
      "scriptId":"u43"},
    "f2a7f39625be4085b36cc1b87a6d28bd":{
      "scriptId":"u44"},
    "3adf2c3e2cda4f4c9c0e5ef139ae07ee":{
      "scriptId":"u45"},
    "78f79e323ea949778d50fb9a51987e83":{
      "scriptId":"u46"},
    "a090043a91b24458b4b4de1188805ef3":{
      "scriptId":"u47"},
    "345ad4fc642d4788a981ed8b90747e31":{
      "scriptId":"u48"},
    "fa8598271257410398f962f7ea9b1ce8":{
      "scriptId":"u49"},
    "73dcf82b85a3490aa99deadf5f1f49d2":{
      "scriptId":"u50"},
    "17c8fd0d9346459ea18a6ed4b26679cc":{
      "scriptId":"u51"},
    "a710ce354f5d40ccad42df475dae14e8":{
      "scriptId":"u52"},
    "b826e2058e80403fae6ae5ad26945e3e":{
      "scriptId":"u53"},
    "f9472209a2bb424ba6a9fe721af43b12":{
      "scriptId":"u54"},
    "7fe85b584ce742dd8618d82809c7cf33":{
      "scriptId":"u55"},
    "836aa7f944e14118a4736fbb59c429b4":{
      "scriptId":"u56"},
    "b8fb2ee2600441d38f4fc2e18a69f291":{
      "scriptId":"u57"},
    "66cd91d9053b4fb29ec6ac9aafe69e8f":{
      "scriptId":"u58"},
    "1d767b0398fa43b18f09d581f02e34f0":{
      "scriptId":"u59"},
    "24b00cd96e1d4740bbd43ed914bafbdf":{
      "scriptId":"u60"},
    "e696b8d2eaf545a9948adfe63642ab8a":{
      "scriptId":"u61"},
    "188a85e9b3574c4aabbe8e2605d9d705":{
      "scriptId":"u62"},
    "754c07cfd8a547bb99cf4e0f892a2735":{
      "scriptId":"u63"}}});