$axure.loadCurrentPage({
  "url":"功能缩放.html",
  "generationDate":new Date(1429602387285.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a2dc09387e5e4676a17f2b578151c6cd",
    "type":"Axure:Page",
    "name":"功能缩放",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ce4912b5c054167bd5cc8561b9f5dbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109.999984741211},
            "size":{
              "width":1136,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"242db4a5a1e14db5bb3d9c70d3fd92be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":109.999984741211},
                "size":{
                  "width":1136,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"46873cb554a14479a2c4475249160a9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":927,
              "y":110},
            "size":{
              "width":83,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce517c8dc3f24b1a8d0c6964ee3cd76c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":927,
                  "y":110},
                "size":{
                  "width":83,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"cfc36d273baa4f5392d63cb2aeb971b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":110},
            "size":{
              "width":106,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f0aee8a4b046a68ba299390edec02d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":110},
                "size":{
                  "width":106,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"0593b13c6e0d4c5c97b0dbef6d0d66a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1010,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad5ca2bcc23a4aa78a739a367d1f441b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1010,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"6a27fe6d4ba047e39491dd1e583f567f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":1010,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d7ef9fb9d0d4504ac5c9a35fd32f8f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":1010,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"be8e9163a00741208a2f5a83c73b3b94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b9891b49a554ebebfee00e2934993f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u10.png"}},
{
          "id":"29305321818d49bd93351593aef62fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43448e052fad47b694fdfcaf46ee506b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":1130,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u12.png"}},
{
          "id":"83363ac474a14e46aaf2ba635de493b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "location":{
              "x":112,
              "y":738},
            "size":{
              "width":438,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a952f3b250a5495cb817a9df37ea3b47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "location":{
                  "x":112,
                  "y":738},
                "size":{
                  "width":438,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"1c23a9d6b94644e3b746e1ec7ba4f064",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":280},
            "size":{
              "width":216,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c785a282b4d34fb3b75f9b0eeb234ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":280},
                "size":{
                  "width":216,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"5bbf74a98c95479e830fbda86f76e17d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":240},
            "size":{
              "width":109,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"267b4503649e4d83b0c002f1a6d49c72",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":240},
            "size":{
              "width":105,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"f84c88a4026840fbb5ed99b9a46f3b0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":797,
              "y":119},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4f9a65883634892b683bb1af7708600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":797,
                  "y":119},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"e71b8147430c4339a82f33692d8e1fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":797,
              "y":142},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7bb8afebee49b584adf4bdc24b5411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":797,
                  "y":142},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u8.png"}},
{
          "id":"2646ee0ed98742e8a27520943580f94f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":1010,
              "y":165},
            "size":{
              "width":130,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ed29499cc34fd0b117900b19753d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":1010,
                  "y":165},
                "size":{
                  "width":130,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u24.png"}},
{
          "id":"888c3325316c48238f6498cfbee89f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":250},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0da9169f6634ea78104828e7612245a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":250},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"3b75d807934d4a99840f07a0d37e23e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f847317dec974310b977e5a63ff2fcd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"ab9e33bd10b44e8d9ce09195cbad4266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ca8846d86647ceb2ec737cbd8e40bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"7fc672fe2552411d8bcf1e9df2d1b285",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c62e9b82ae9e47c1a0dabf995ac55185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"4018ba08abd84ca384017b87af73b4ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":110},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06dd8f21506f469bb4929d45e49854ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":110},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"526c8aa066b44fa5b4a7585ad291abb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":558},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0102bbb3d880418a93b73a5a71b93325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":558},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"c47dbbbf581e4e4f97dbfeb370850adf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80f5ef1e3b934271bbba23a4b06c719f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u26.png"}},
{
          "id":"a49f735aa26e4d3db55f6166009b92ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1216,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11801b43008544ff9f8b74f720986a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1216,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"5665753775664665bb9ecb7abe551e77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":160},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fae2a1c2e6cc4b988109828008b8a40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":160},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u40.png"}},
{
          "id":"a66b5e0c11514417b6a46b0bd7a04d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":136},
            "size":{
              "width":115,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2f613d1e8547b6b9e0788c40e48039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":136},
                "size":{
                  "width":115,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u44.png"}},
{
          "id":"f2f26566a11b4e8587697fb8f5bbf9f5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1069,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"665ed9067fc049769868d2178711a51b",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":570},
            "size":{
              "width":328,
              "height":168}},
          "adaptiveStyles":{
}},
{
          "id":"fc334d9e8ebb47259c30b3f3f6fc52f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"309d5bfaee97489281ddfaa06922c693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"13dc6e5191dd494497059f59138519ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02b259fbe2eb47adba0e9061bf82e28f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"28e07fe66e1a46c7b2c0607ba6315e7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d880521564b14e30a0a7ef002b16edb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"94f0b54590a94f28ad6a1884801f319b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":540},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c35241b2e0aa4794b8d5a72e57df8e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":540},
                "size":{
                  "width":70,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u48.png"}},
{
          "id":"c9cc8b72475445699c62711295f63a74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":703},
            "size":{
              "width":976,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"113d222c325645368c660ae7d0e040bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":703},
                "size":{
                  "width":976,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u56.png"}},
{
          "id":"2bb39e01fac846ca953ce0839836a5c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":171},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4daec30c9d49430fa00c34cf0fa231e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":171},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"2718912db52d41aaac8150e408638896",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":111},
            "size":{
              "width":115,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03495b92c5c44d52b48b5a46c59a102d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":111},
                "size":{
                  "width":115,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u58.png"}},
{
          "id":"3148338328f143ed94fb0693b2297fa5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":280},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e928ba27e06040989b99ab1336f7dbcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":280},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"3345fc0d764146c2a8e896165b62a299",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":320},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8a7367b5c1547bbaf33804b6e8bfde3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":320},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"7f04236996084b149c7eb38e2dacccc4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":360},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4dca5970d3149cb80629788372b7f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":360},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"9ff630ba36b34ab58408da9935f037ef",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":400},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fb16267c4294c1d8b90a6c811306d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":400},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"fdb181ada7bd4d70b3e0b482018d6ab8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1031,
              "y":440},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93665eae32f54af5bff34e89f0944cd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1031,
                  "y":440},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u62.png"}},
{
          "id":"d4e216e0ef9d46b59727d4b23c95eb29",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":1156,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0b2643e80148a7bee912919c2149d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":1156,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"7786e8e37bfc4bc59f3ace684c9c1969",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":1066,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed48616391924ba68e1cf99fe026f414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":1066,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"2a7520cfbd9c4d518489d6555a7e54f9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":976,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"985f633ca21340b1927ed894babdb596",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":976,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"36a1a134306640dab5ef332c86931af6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":886,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22138b8d8fe748628c09a939787190d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":886,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"c731dd264e23402b86018eacb2ec70ae",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":796,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"855111b493234f79ae739c049ab2228d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":796,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"ac6acabf9e364465beb29cc1d66610ec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":706,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abce51f1a4034c3c9bc41364a1e01135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":706,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}},
{
          "id":"534a63cea44646ab8b3007005c787b5d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":648},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d090f39d9adf44d7a1a4b835c0644ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":648},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8ce4912b5c054167bd5cc8561b9f5dbc":{
      "scriptId":"u0"},
    "242db4a5a1e14db5bb3d9c70d3fd92be":{
      "scriptId":"u1"},
    "46873cb554a14479a2c4475249160a9d":{
      "scriptId":"u2"},
    "ce517c8dc3f24b1a8d0c6964ee3cd76c":{
      "scriptId":"u3"},
    "cfc36d273baa4f5392d63cb2aeb971b3":{
      "scriptId":"u4"},
    "53f0aee8a4b046a68ba299390edec02d":{
      "scriptId":"u5"},
    "0593b13c6e0d4c5c97b0dbef6d0d66a2":{
      "scriptId":"u6"},
    "ad5ca2bcc23a4aa78a739a367d1f441b":{
      "scriptId":"u7"},
    "6a27fe6d4ba047e39491dd1e583f567f":{
      "scriptId":"u8"},
    "2d7ef9fb9d0d4504ac5c9a35fd32f8f9":{
      "scriptId":"u9"},
    "be8e9163a00741208a2f5a83c73b3b94":{
      "scriptId":"u10"},
    "2b9891b49a554ebebfee00e2934993f1":{
      "scriptId":"u11"},
    "29305321818d49bd93351593aef62fe6":{
      "scriptId":"u12"},
    "43448e052fad47b694fdfcaf46ee506b":{
      "scriptId":"u13"},
    "83363ac474a14e46aaf2ba635de493b7":{
      "scriptId":"u14"},
    "a952f3b250a5495cb817a9df37ea3b47":{
      "scriptId":"u15"},
    "1c23a9d6b94644e3b746e1ec7ba4f064":{
      "scriptId":"u16"},
    "c785a282b4d34fb3b75f9b0eeb234ef4":{
      "scriptId":"u17"},
    "5bbf74a98c95479e830fbda86f76e17d":{
      "scriptId":"u18"},
    "267b4503649e4d83b0c002f1a6d49c72":{
      "scriptId":"u19"},
    "f84c88a4026840fbb5ed99b9a46f3b0d":{
      "scriptId":"u20"},
    "c4f9a65883634892b683bb1af7708600":{
      "scriptId":"u21"},
    "e71b8147430c4339a82f33692d8e1fcf":{
      "scriptId":"u22"},
    "5a7bb8afebee49b584adf4bdc24b5411":{
      "scriptId":"u23"},
    "2646ee0ed98742e8a27520943580f94f":{
      "scriptId":"u24"},
    "e1ed29499cc34fd0b117900b19753d68":{
      "scriptId":"u25"},
    "888c3325316c48238f6498cfbee89f2f":{
      "scriptId":"u26"},
    "c0da9169f6634ea78104828e7612245a":{
      "scriptId":"u27"},
    "3b75d807934d4a99840f07a0d37e23e7":{
      "scriptId":"u28"},
    "f847317dec974310b977e5a63ff2fcd5":{
      "scriptId":"u29"},
    "ab9e33bd10b44e8d9ce09195cbad4266":{
      "scriptId":"u30"},
    "c3ca8846d86647ceb2ec737cbd8e40bd":{
      "scriptId":"u31"},
    "7fc672fe2552411d8bcf1e9df2d1b285":{
      "scriptId":"u32"},
    "c62e9b82ae9e47c1a0dabf995ac55185":{
      "scriptId":"u33"},
    "4018ba08abd84ca384017b87af73b4ed":{
      "scriptId":"u34"},
    "06dd8f21506f469bb4929d45e49854ca":{
      "scriptId":"u35"},
    "526c8aa066b44fa5b4a7585ad291abb8":{
      "scriptId":"u36"},
    "0102bbb3d880418a93b73a5a71b93325":{
      "scriptId":"u37"},
    "c47dbbbf581e4e4f97dbfeb370850adf":{
      "scriptId":"u38"},
    "80f5ef1e3b934271bbba23a4b06c719f":{
      "scriptId":"u39"},
    "a49f735aa26e4d3db55f6166009b92ee":{
      "scriptId":"u40"},
    "11801b43008544ff9f8b74f720986a1b":{
      "scriptId":"u41"},
    "5665753775664665bb9ecb7abe551e77":{
      "scriptId":"u42"},
    "fae2a1c2e6cc4b988109828008b8a40b":{
      "scriptId":"u43"},
    "a66b5e0c11514417b6a46b0bd7a04d8f":{
      "scriptId":"u44"},
    "8f2f613d1e8547b6b9e0788c40e48039":{
      "scriptId":"u45"},
    "f2f26566a11b4e8587697fb8f5bbf9f5":{
      "scriptId":"u46"},
    "665ed9067fc049769868d2178711a51b":{
      "scriptId":"u47"},
    "fc334d9e8ebb47259c30b3f3f6fc52f7":{
      "scriptId":"u48"},
    "309d5bfaee97489281ddfaa06922c693":{
      "scriptId":"u49"},
    "13dc6e5191dd494497059f59138519ba":{
      "scriptId":"u50"},
    "02b259fbe2eb47adba0e9061bf82e28f":{
      "scriptId":"u51"},
    "28e07fe66e1a46c7b2c0607ba6315e7c":{
      "scriptId":"u52"},
    "d880521564b14e30a0a7ef002b16edb0":{
      "scriptId":"u53"},
    "94f0b54590a94f28ad6a1884801f319b":{
      "scriptId":"u54"},
    "c35241b2e0aa4794b8d5a72e57df8e74":{
      "scriptId":"u55"},
    "c9cc8b72475445699c62711295f63a74":{
      "scriptId":"u56"},
    "113d222c325645368c660ae7d0e040bb":{
      "scriptId":"u57"},
    "2bb39e01fac846ca953ce0839836a5c9":{
      "scriptId":"u58"},
    "4daec30c9d49430fa00c34cf0fa231e1":{
      "scriptId":"u59"},
    "2718912db52d41aaac8150e408638896":{
      "scriptId":"u60"},
    "03495b92c5c44d52b48b5a46c59a102d":{
      "scriptId":"u61"},
    "3148338328f143ed94fb0693b2297fa5":{
      "scriptId":"u62"},
    "e928ba27e06040989b99ab1336f7dbcd":{
      "scriptId":"u63"},
    "3345fc0d764146c2a8e896165b62a299":{
      "scriptId":"u64"},
    "c8a7367b5c1547bbaf33804b6e8bfde3":{
      "scriptId":"u65"},
    "7f04236996084b149c7eb38e2dacccc4":{
      "scriptId":"u66"},
    "f4dca5970d3149cb80629788372b7f40":{
      "scriptId":"u67"},
    "9ff630ba36b34ab58408da9935f037ef":{
      "scriptId":"u68"},
    "3fb16267c4294c1d8b90a6c811306d8f":{
      "scriptId":"u69"},
    "fdb181ada7bd4d70b3e0b482018d6ab8":{
      "scriptId":"u70"},
    "93665eae32f54af5bff34e89f0944cd8":{
      "scriptId":"u71"},
    "d4e216e0ef9d46b59727d4b23c95eb29":{
      "scriptId":"u72"},
    "5f0b2643e80148a7bee912919c2149d0":{
      "scriptId":"u73"},
    "7786e8e37bfc4bc59f3ace684c9c1969":{
      "scriptId":"u74"},
    "ed48616391924ba68e1cf99fe026f414":{
      "scriptId":"u75"},
    "2a7520cfbd9c4d518489d6555a7e54f9":{
      "scriptId":"u76"},
    "985f633ca21340b1927ed894babdb596":{
      "scriptId":"u77"},
    "36a1a134306640dab5ef332c86931af6":{
      "scriptId":"u78"},
    "22138b8d8fe748628c09a939787190d1":{
      "scriptId":"u79"},
    "c731dd264e23402b86018eacb2ec70ae":{
      "scriptId":"u80"},
    "855111b493234f79ae739c049ab2228d":{
      "scriptId":"u81"},
    "ac6acabf9e364465beb29cc1d66610ec":{
      "scriptId":"u82"},
    "abce51f1a4034c3c9bc41364a1e01135":{
      "scriptId":"u83"},
    "534a63cea44646ab8b3007005c787b5d":{
      "scriptId":"u84"},
    "d090f39d9adf44d7a1a4b835c0644ff6":{
      "scriptId":"u85"}}});