# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeExpandImportedTargets.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CheckFunctionExists.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CheckIncludeFile.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CheckIncludeFileCXX.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CheckLibraryExists.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CheckTypeSize.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-C.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-CXX.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindBZip2.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindZLIB.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-C.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-CXX.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/SelectLibraryConfigurations.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/CMakeLists.txt\
/Users/magicstudio/Public/3rd/pcre-8.31/cmake/FindEditline.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/cmake/FindPackageHandleStandardArgs.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/cmake/FindReadline.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/config-cmake.h.in\
/Users/magicstudio/Public/3rd/pcre-8.31/pcre.h.in\
/Users/magicstudio/Public/3rd/pcre-8.31/pcre_chartables.c.dist\
/Users/magicstudio/Public/3rd/pcre-8.31/prj/CMakeFiles/CMakeCCompiler.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/prj/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/magicstudio/Public/3rd/pcre-8.31/prj/CMakeFiles/CMakeSystem.cmake
	/Applications/CMake\ 2.8-9.app/Contents/bin/cmake -H/Users/magicstudio/Public/3rd/pcre-8.31 -B/Users/magicstudio/Public/3rd/pcre-8.31/prj
