//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParticleSystemEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ParticleSystemETYPE         129
#define IDD_VIEW_PARTICLEPARAMETER      130
#define IDD_DIALOG_TEXTUREWND           131
#define IDD_DIALOG_PARTICLEPATHWND      132
#define IDR_MENU1                       133
#define IDD_DIALOG_TextInputDlg         134
#define IDC_CURSOR_4WAY                 135
#define IDC_CURSOR_EW                   136
#define IDC_CURSOR_MOVE                 137
#define IDC_CURSOR_NS                   138
#define IDC_CURSOR_ROTATE               139
#define IDC_CURSOR_INS                  140
#define IDI_ICON_MYPLUS                 141
#define IDD_DIALOG_TestManager          144
#define IDD_DIALOG_PSPARAMETERDLG       145
#define IDR_MENU2                       146
#define IDD_DIALOG_SETEFFECTGROUPNAME   147
#define IDD_DIALOG_PARAMETERADJUST      148
#define IDR_MENU3                       149
#define IDR_MENU_TEXTUREWND             152
#define IDR_MENU_TextureListCtrl        153
#define IDD_DIALOG_mnPicTestDlg         154
#define IDD_DIALOG_PSANI_PARAMDLG       155
#define IDD_DIALOG_SetPSLinfoParam      156
#define IDD_DIALOG_BasicSysParam        157
#define IDD_DIALOG_EmitterParam         158
#define IDD_DIALOG_ParticleParam        159
#define IDD_DIALOG_SpecialParticleParam 160
#define IDR_TOOLBAR_PARTICLESYS         162
#define IDC_BUTTON_START                998
#define IDC_BUTTON_STOP                 999
#define IDC_BUTTON_LOADTEXTURE          1000
#define IDC_SLIDER_SYSTEMPOSITION_POSX  1001
#define IDC_SLIDER_SYSTEMPOSITION_POSY  1002
#define IDC_SLIDER_SYSTEMPOSITION_POSX2 1003
#define IDC_SLIDER_SYSTEMPOSITION_POSY2 1004
#define IDC_SLIDER_SYSTEMLIFETIME       1005
#define IDC_SLIDER_SYSMAXPARTICLES      1006
#define IDC_SLIDER_SYSTEMEMISSIONRATE   1007
#define IDC_SLIDER_PARTICLELIFETIME_MIN 1008
#define IDC_SLIDER_PARTICLELIFETIME_MAX 1009
#define IDC_SLIDER_EMISSIONDIRECTION    1010
#define IDC_SLIDER_EMISSIONSPREAD       1011
#define IDC_SLIDER_STARTSPEED_MIN       1012
#define IDC_SLIDER_STARTSPEED_MAX       1013
#define IDC_SLIDER_GRAVITY              1014
#define IDC_SLIDER_GRAVITY_RAND         1015
#define IDC_SLIDER_RADIALACCELERATION   1016
#define IDC_SLIDER_RADIALACCELERATION_RAND 1017
#define IDC_SLIDER_TANGACC              1018
#define IDC_SLIDER_TANGACC_RAND         1019
#define IDC_SLIDER_PARTICLESIZE_STRTX   1020
#define IDC_SLIDER_PARTICLESIZE_STRTY   1021
#define IDC_SLIDER_PARTICLESIZE_ENDX    1022
#define IDC_SLIDER_PARTICLESIZE_ENDY    1023
#define IDC_SLIDER_PARTICLESIZE_VAR     1024
#define IDC_SLIDER_PARTICLESPIN_STRT    1025
#define IDC_SLIDER_PARTICLESPIN_END     1026
#define IDC_SLIDER_PARTICLESPIN_VAR     1027
#define IDC_SLIDER_PARTICLEANGLE_STRT   1028
#define IDC_SLIDER_PARTICLEANGLE_END    1029
#define IDC_SLIDER_PARTICLEANGLE_VAR    1030
#define IDC_SLIDER_PARTICLEALPHA_STRT   1031
#define IDC_SLIDER_PARTICLEALPHA_END    1032
#define IDC_SLIDER_PARTICLEALPHA_VAR    1033
#define IDC_SLIDER_SYSTEMPOSITION_RADIUSX 1034
#define IDC_SLIDER_SYSTEMPOSITION_RADIUSY 1035
#define IDC_SLIDER_SYSTEMPOSITION_POSWIDTH 1036
#define IDC_SLIDER_SYSTEMPOSITION_POSHEIGHT 1037
#define IDC_SLIDER_ANIPLAYSPEED         1038
#define IDC_SLIDER_SIZERAND             1039
#define IDC_SLIDER_SPINRANDOM           1040
#define IDC_SLIDER_ANGLERANDOM          1041
#define IDC_SLIDER_AlignToMotionAngle   1042
#define IDC_SLIDER_EMITTERSPEED         1043
#define IDC_SLIDER_AniSpeedRand         1044
#define IDC_SLIDER_PARTICLECOLOR_STRT_R 1045
#define IDC_SLIDER_PARTICLECOLOR_STRT_G 1046
#define IDC_SLIDER_PARTICLECOLOR_STRT_B 1047
#define IDC_SLIDER_PARTICLECOLOR_END_R  1048
#define IDC_SLIDER_PARTICLECOLOR_END_G  1049
#define IDC_SLIDER_PARTICLECOLOR_END_B  1050
#define IDC_SLIDER_PARTICLECOLOR_VAR    1051
#define IDC_SLIDER_PSLZOOM              1052
#define IDC_SLIDER_EMITTERSPIN          1053
#define IDC_SLIDER_VERTEXROW            1054
#define IDC_SLIDER_VERTEXCOL            1055
#define IDC_CHECK_FILLMODE              1060
#define IDC_CHECK_EMITTERTYPE           1061
#define IDC_LIST_TEXTURE                1063
#define IDC_BUTTON_SETCUSTOMPATH        1064
#define IDC_CHECK_ADDPOINT              1066
#define IDC_CHECK_MOVEPOINT             1067
#define IDC_BUTTON_RESET                1068
#define IDC_BUTTON_SAVEPATH             1069
#define IDC_BUTTON_LOADPATH             1070
#define IDC_CHECK_CurveAdjust           1071
#define IDC_CHECK_ORDER                 1072
#define IDC_BUTTON_SetVectorChar        1073
#define IDC_EDIT_InputText              1074
#define IDC_COMBO_FontName              1075
#define IDC_EDIT_FontSpace              1076
#define IDC_EDIT_FontHeight             1077
#define IDC_CHECK_LoadVectorChar        1078
#define IDC_EDIT_FontAngle              1079
#define IDC_CHECK_COLORCHANGE           1080
#define IDC_CHECK_OBJTRACK              1081
#define IDC_COMBO_PSLTYPE               1082
#define IDC_BUTTON_TestManager          1083
#define IDC_EDIT_LAYER                  1086
#define IDC_SLIDER_posx                 1087
#define IDC_SLIDER_posy                 1088
#define IDC_SLIDER_trackobjectx         1089
#define IDC_SLIDER_trackobjecty         1090
#define IDC_RADIO_BLEND                 1091
#define IDC_RADIO_ADD                   1092
#define IDC_RADIO_ONEADD                1093
#define IDC_Tree_ParticleSysList        1094
#define IDC_BUTTON_psParamColor         1095
#define IDC_BUTTON_Replay               1096
#define IDC_CHECK_CYCLE                 1097
#define IDC_COMBO_EffectType            1098
#define IDC_CHECK_LinkAngleUV           1099
#define IDC_CHECK_SingleParticleAni     1100
#define IDC_EDIT_EFFECTGROUPNAME        1103
#define IDC_CHECK_ALIGNTOMOTION         1104
#define IDC_CHECK_ALIGNTOEMITTER        1105
#define IDC_TREE_ParameterList          1106
#define IDC_STATIC_ParameterCurve       1107
#define IDC_EDIT_SysPosX                1108
#define IDC_EDIT_SysPosY                1109
#define IDC_EDIT_SysPosX2               1110
#define IDC_EDIT_SysPosY2               1111
#define IDC_EDIT_SysPosRadiusX          1112
#define IDC_EDIT_SysPosRadiusY          1113
#define IDC_EDIT_SysPosWidth            1114
#define IDC_EDIT_SysPosHeight           1115
#define IDC_EDIT_SysLife                1116
#define IDC_EDIT_SysMaxParticles        1117
#define IDC_EDIT_EmissionRate           1118
#define IDC_EDIT_ParticleLifeMin        1119
#define IDC_EDIT_ParticleLifeMax        1120
#define IDC_EDIT_EmissionDirection      1121
#define IDC_EDIT_EmissionSpread         1122
#define IDC_EDIT_SpeedMin               1123
#define IDC_EDIT_SpeedMax               1124
#define IDC_EDIT_AniPlaySpeed           1125
#define IDC_EDIT_Gravity                1126
#define IDC_EDIT_GravityRand            1127
#define IDC_EDIT_RadialAcc              1128
#define IDC_EDIT_RadialAccRand          1129
#define IDC_EDIT_TangAcc                1130
#define IDC_EDIT_TangAccRand            1131
#define IDC_EDIT_ParSizeStrtX           1132
#define IDC_EDIT_ParSizeStrtY           1133
#define IDC_EDIT_ParSizeEndX            1134
#define IDC_EDIT_ParSizeEndY            1135
#define IDC_EDIT_ParSizeVar             1136
#define IDC_EDIT_SizeRandom             1137
#define IDC_EDIT_ParSpinStrt            1138
#define IDC_EDIT_ParSpinEnd             1139
#define IDC_EDIT_ParSpinVar             1140
#define IDC_EDIT_SpinRandom             1141
#define IDC_EDIT_AlignToMotionAngle     1142
#define IDC_EDIT_ParAngleStrt           1143
#define IDC_EDIT_ParAngleEnd            1144
#define IDC_EDIT_ParAngleVar            1145
#define IDC_EDIT_AngleRandom            1146
#define IDC_EDIT_ParAlphaStrt           1147
#define IDC_EDIT_ParAlphaEnd            1148
#define IDC_EDIT_ParAlphaVar            1149
#define IDC_EDIT_ParColorStrtR          1150
#define IDC_EDIT_ParColorStrtG          1151
#define IDC_EDIT_ParColorStrtB          1152
#define IDC_EDIT_ParColorEndR           1153
#define IDC_EDIT_ParColorEndG           1154
#define IDC_EDIT_ParColorEndB           1155
#define IDC_EDIT_ParColorVar            1156
#define IDC_EDIT_ParAlphaMid            1157
#define IDC_EDIT_ParAlphaMidTime        1158
#define IDC_EDIT_EMITTERSPEED           1159
#define IDC_EDIT_AniSpeedRand           1160
#define IDC_EDIT_PSLZOOM                1161
#define IDC_EDIT_EMITTERSPIN            1162
#define IDC_EDIT_VertexRow              1163
#define IDC_EDIT_VertexCol              1164
#define IDC_EDIT_LineAngle              1165
#define IDC_CHECK_MoveBKPic             1170
#define IDC_CHECK_MoveBKMap             1171
#define IDC_SLIDER_ParAlphaMid          1172
#define IDC_BUTTON_SetBkMap             1173
#define IDC_SLIDER_ParAlphaMidTime      1174
#define IDC_BUTTON_Refresh              1175
#define IDC_PICTURE_RotateCenterSetWnd  1176
#define IDC_ResetRotateCenterPos        1177
#define IDC_PICTURE_DRAWPATHRCT         1178
#define IDC_COMBO_ParticlePathInitPos   1179
#define IDC_CHECK_MOVEMAP               1180
#define IDC_CHECK_AlignToPath           1181
#define IDC_CHECK_ShowGrid              1182
#define IDC_PICTURE_DRAWPARTICLES       1183
#define IDC_CHECK_UVMIRRORV             1184
#define IDC_CHECK_RANDANGLE             1185
#define IDC_SLIDER_PATHSPIN             1186
#define IDC_SLIDER_PATHZOOM             1187
#define IDC_EDIT_EmitterAngle           1187
#define IDC_CHECK_UVMIRRORH             1188
#define IDC_EDIT_PathZoom               1189
#define IDC_CHECK_SetEmitterSpinCenter  1189
#define IDC_EDIT_PATHSPIN               1190
#define IDC_CHECK_SetParticleHole       1190
#define IDC_CHECK_MotionToPath          1191
#define IDC_CHECK_AlignToParticleHole   1192
#define IDC_COMBO_PATHMIRRORTYPE        1193
#define IDC_CHECK_RANDANGLESELF         1193
#define IDC_BUTTON_PSLGfileVERconversion 1194
#define IDC_CHECK_MOVEEFFECT            1195
#define IDC_TREE_PSLTEXTURELIST         1196
#define IDC_COMBO_SIZERANDTYPE          1197
#define IDC_CHECK_MAXBOXFLAG            1199
#define IDC_COMBO_CONFIGUREREQUIRE      1200
#define IDC_COMBO_COMPUTERCONFIG        1201
#define IDC_CHECK_AbstractPsl           1202
#define IDC_CHECK_DIRmotion             1203
#define IDC_BUTTON_STARTCOLOR           1204
#define IDC_BUTTON_ENDCOLOR             1205
#define IDC_BUTTON_FINDPSLTEXTURES      1206
#define IDC_CHECK_RandColor             1207
#define IDC_BUTTON_SetShapeTexture      1212
#define IDC_CHECK_CreatePologyOK        1213
#define IDC_BUTTON_LoadVertex           1214
#define IDC_BUTTON_SaveVertex           1215
#define IDC_CHECK_LINKCOLOR             1216
#define IDC_COMBO_ApslVertexType        1217
#define IDC_CHECK1                      1221
#define IDC_CHECK_ParticleANI_1         1221
#define IDC_CHECK_MaxParticles          1221
#define IDC_CHECK_InterfacialEffect     1221
#define IDC_CHECK_CurveSample           1221
#define IDC_CHECK_                      1221
#define IDC_CHECK_LineEmiterDemo        1221
#define IDC_BUTTON_mnPICtest            1222
#define IDC_BUTTON_SETFILEPATH          1223
#define IDC_CHECK_InterfacialEffect2    1223
#define IDC_CHECK_skillEffectBottom     1223
#define IDC_EDIT_ROW                    1224
#define IDC_EDIT_COL                    1225
#define IDC_EDIT_FILEPATH               1226
#define IDC_BUTTON_SAVEMODIFYPSL        1227
#define IDC_BUTTON_PrintPSANI           1228
#define IDC_EDIT_psAniSpeed             1229
#define IDC_COMBO_PicFileFormat         1230
#define IDC_RADIO1                      1231
#define IDC_RADIO2                      1232
#define IDC_PICTURECTRL_PARTICLECOLOR   1233
#define IDC_BUTTON_OPENPARTICLESYS      1234
#define IDC_BUTTON_SAVEPARTICLESYS      1235
#define IDC_BUTTON_RESETPARTICLESYS     1236
#define IDC_COMBO_BLENDMODE_SRC         1237
#define IDC_BUTTON_SAMPLE1              1238
#define IDC_BUTTON_SAMPLE2              1239
#define IDC_BUTTON_SAMPLE3              1240
#define IDC_BUTTON_SAMPLE4              1241
#define IDC_BUTTON_SAMPLE5              1242
#define IDC_BUTTON_SAMPLE6              1243
#define IDC_BUTTON_SAMPLE7              1244
#define IDC_BUTTON_SAMPLE8              1245
#define IDC_BUTTON_SAMPLE9              1246
#define IDC_BUTTON_SAMPLE10             1247
#define IDC_CHECK_LINKLIFETIME          1248
#define IDC_CHECK_LINKSPEED             1249
#define IDC_BUTTON_StrtANI              1250
#define IDC_BUTTON_EndANI               1251
#define IDC_BUTTON_PslFileInfo          1252
#define IDC_CHECK_LINKSIZE              1253
#define IDC_EDIT_MaxParticles           1253
#define IDC_CHECK_LINKSPIN              1254
#define IDC_CHECK_LINKALPHA             1255
#define IDC_COMBO_BLENDMODE_DES         1256
#define IDC_TAB_ParticleParams          1256
#define IDC_BUTTON_SETBKCOLOR           1257
#define IDC_CHECK_SHOWBKPIC             1258
#define IDC_CHECK_FullScreen            1258
#define IDC_BUTTON_SETBKPIC             1259
#define IDC_CHECK_SpecialPS             1259
#define IDC_CHECK_MultTextures          1260
#define IDC_SLIDER_LineLength           1260
#define IDC_CHECK_CustomPath            1261
#define IDC_SLIDER_RctWidth             1261
#define IDC_CHECK_AlphaADD              1262
#define IDC_SLIDER_RctHeight            1262
#define IDC_EDIT_LineLength             1263
#define IDC_EDIT_RctWidth               1264
#define IDC_EDIT_RctHeight              1265
#define IDC_CHECK_BlindArea             1266
#define IDC_CHECK_BlockLine             1267
#define IDC_CHECK_ReflectLine           1268
#define IDC_BUTTON_OpenParamFile        1269
#define IDC_BUTTON2                     1270
#define IDC_BUTTON_SaveParamFile        1270
#define IDC_RADIO_LOW                   1271
#define IDC_RADIO_MIDDLE                1272
#define IDC_RADIO_HIGH                  1273
#define IDC_BUTTON_AllPSLtoPTC          1274
#define IDC_SAVE_CONFIGPARAM            1275
#define IDC_SLIDER_LineAngle            1275
#define IDC_BUTTON_FromTextureListFindPsl 1276
#define IDC_EDIT_TextureRow             1277
#define IDC_EDIT_TextureCol             1278
#define IDC_EDIT1                       1279
#define IDC_EDIT_TextureCount           1279
#define ID_NENU_DELPOINT                32771
#define ID_NENU_CURVE                   32772
#define ID_NENU_LINK                    32773
#define ID_MENU_AddParticleSys          32779
#define ID_MENU_DelParticleSys          32780
#define ID_MENU_ModifyParticleSys       32781
#define ID_MENU_AddEffectGroup          32782
#define ID_MENU_DELEFFECTGROUP          32784
#define ID_MENU_MODIFYGROUPNAME         32785
#define ID_MENU_SAVEEFFECTGROUP         32788
#define ID_MENU_LAODEFFECTGROUP         32790
#define ID_MENU_PROPERTIES              32791
#define ID_MENU_pslPROPERTY             32793
#define ID_MENU_PSreplay                32794
#define ID_MENU_COPYPATH                32796
#define ID_MENU_REFRESHTEXTURE          32797
#define ID_MENU_COPYFULLPATH            32799
#define ID_MENU_KEYPOINT                32800
#define ID_BUTTON_OPENPSL               32806
#define ID_BUTTON_SAVEPSL               32807
#define ID_BUTTON_SAVEASPSL             32809
#define ID_Menu                         32811
#define ID_BTN_TGA2DDS                  32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1280
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
