
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 此头文件包含当前名字空间下的所有协议。要注意，如果把实现写在头文件里面，
// 包含这个头文件很容易产生循环。

#include "gnet/link/AnnounceLinkId.hpp"
#include "gnet/link/Bind.hpp"
#include "gnet/link/Broadcast.hpp"
#include "gnet/link/Dispatch.hpp"
#include "gnet/link/Kick.hpp"
#include "gnet/link/LinkBroken.hpp"
#include "gnet/link/LinkServerControl.hpp"
#include "gnet/link/Send.hpp"
#include "gnet/link/SetLogin.hpp"
#include "gnet/link/UnBind.hpp"
