LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := ceguibase_static

LOCAL_MODULE_FILENAME := libceguibase

LOCAL_SRC_FILES := \
	../CEGUI/src/CEGUIBase.cpp \
	../CEGUI/src/CEGUIAffector.cpp \
	../CEGUI/src/CEGUIAnimation.cpp \
	../CEGUI/src/CEGUIAnimationInstance.cpp \
	../CEGUI/src/CEGUIAnimationManager.cpp \
	../CEGUI/src/CEGUIAnimation_xmlHandler.cpp \
	../CEGUI/src/CEGUIBasicInterpolators.cpp \
	../CEGUI/src/CEGUIBasicRenderedStringParser.cpp \
	../CEGUI/src/CEGUIBiDiVisualMapping.cpp \
	../CEGUI/src/CEGUIBoundSlot.cpp \
	../CEGUI/src/CEGUICentredRenderedString.cpp \
	../CEGUI/src/CEGUIChainedXMLHandler.cpp \
	../CEGUI/src/CEGUIColourRect.cpp \
	../CEGUI/src/CEGUIConfig_xmlHandler.cpp \
	../CEGUI/src/CEGUICoordConverter.cpp \
	../CEGUI/src/CEGUIDataContainer.cpp \
	../CEGUI/src/CEGUIDefaultLogger.cpp \
	../CEGUI/src/CEGUIDefaultRenderedStringParser.cpp \
	../CEGUI/src/CEGUIDefaultResourceProvider.cpp \
	../CEGUI/src/CEGUIDynamicModule.cpp \
	../CEGUI/src/CEGUIEditboxStringParser.cpp \
	../CEGUI/src/CEGUIEvent.cpp \
	../CEGUI/src/CEGUIEventArgs.cpp \
	../CEGUI/src/CEGUIEventSet.cpp \
	../CEGUI/src/CEGUIEventSignal.cpp \
	../CEGUI/src/CEGUIEventSignalSet.cpp \
	../CEGUI/src/CEGUIExceptions.cpp \
	../CEGUI/src/CEGUIFactoryModule.cpp \
	../CEGUI/src/CEGUIFont.cpp \
	../CEGUI/src/CEGUIFontManager.cpp \
	../CEGUI/src/CEGUIFontProperties.cpp \
	../CEGUI/src/CEGUIFont_xmlHandler.cpp \
	../CEGUI/src/CEGUIFormattedRenderedString.cpp \
	../CEGUI/src/CEGUIFreeTypeFont.cpp \
	../CEGUI/src/CEGUIFribidiVisualMapping.cpp \
	../CEGUI/src/CEGUIGUILayout_xmlHandler.cpp \
	../CEGUI/src/CEGUIGlobalEventSet.cpp \
	../CEGUI/src/CEGUIImage.cpp \
	../CEGUI/src/CEGUIImageCodec.cpp \
	../CEGUI/src/CEGUIImageset.cpp \
	../CEGUI/src/CEGUIImagesetManager.cpp \
	../CEGUI/src/CEGUIImageset_xmlHandler.cpp \
	../CEGUI/src/CEGUIJustifiedRenderedString.cpp \
	../CEGUI/src/CEGUIJustifiedRenderedStringWordWrapper.cpp \
	../CEGUI/src/CEGUIKeyFrame.cpp \
	../CEGUI/src/CEGUILeftAlignedRenderedString.cpp \
	../CEGUI/src/CEGUILogger.cpp \
	../CEGUI/src/CEGUIMinibidiVisualMapping.cpp \
	../CEGUI/src/CEGUIMouseCursor.cpp \
	../CEGUI/src/CEGUINamedXMLResourceManager.cpp \
	../CEGUI/src/CEGUIPCRERegexMatcher.cpp \
	../CEGUI/src/CEGUIPfsResourceProvider.cpp \
	../CEGUI/src/CEGUIPixmapFont.cpp \
	../CEGUI/src/CEGUIProperty.cpp \
	../CEGUI/src/CEGUIPropertyHelper.cpp \
	../CEGUI/src/CEGUIPropertySet.cpp \
	../CEGUI/src/CEGUIRect.cpp \
	../CEGUI/src/CEGUIRenderQueue.cpp \
	../CEGUI/src/CEGUIRenderedString.cpp \
	../CEGUI/src/CEGUIRenderedStringComponent.cpp \
	../CEGUI/src/CEGUIRenderedStringImageComponent.cpp \
	../CEGUI/src/CEGUIRenderedStringTextComponent.cpp \
	../CEGUI/src/CEGUIRenderedStringWidgetComponent.cpp \
	../CEGUI/src/CEGUIRenderingRoot.cpp \
	../CEGUI/src/CEGUIRenderingSurface.cpp \
	../CEGUI/src/CEGUIRenderingWindow.cpp \
	../CEGUI/src/CEGUIRichEditbox_xmlHandler.cpp \
	../CEGUI/src/CEGUIRightAlignedRenderedString.cpp \
	../CEGUI/src/CEGUIScheme.cpp \
	../CEGUI/src/CEGUISchemeManager.cpp \
	../CEGUI/src/CEGUIScheme_xmlHandler.cpp \
	../CEGUI/src/CEGUIScriptModule.cpp \
	../CEGUI/src/CEGUISize.cpp \
	../CEGUI/src/CEGUISpecialTreeItem_xmlHandler.cpp \
	../CEGUI/src/CEGUIString.cpp \
	../CEGUI/src/CEGUISubscriberSlot.cpp \
	../CEGUI/src/CEGUISystem.cpp \
	../CEGUI/src/CEGUITextUtils.cpp \
	../CEGUI/src/CEGUIWRFactoryRegisterer.cpp \
	../CEGUI/src/CEGUIWindow.cpp \
	../CEGUI/src/CEGUIWindowFactory.cpp \
	../CEGUI/src/CEGUIWindowFactoryManager.cpp \
	../CEGUI/src/CEGUIWindowManager.cpp \
	../CEGUI/src/CEGUIWindowProperties.cpp \
	../CEGUI/src/CEGUIWindowRenderer.cpp \
	../CEGUI/src/CEGUIWindowRendererManager.cpp \
	../CEGUI/src/CEGUIWindowRendererModule.cpp \
	../CEGUI/src/CEGUIXMLAttributes.cpp \
	../CEGUI/src/CEGUIXMLHandler.cpp \
	../CEGUI/src/CEGUIXMLParser.cpp \
	../CEGUI/src/CEGUIXMLSerializer.cpp \
	../CEGUI/src/CEGUIcolour.cpp \
	../CEGUI/src/CEGUIResLoadThread.cpp \
	../CEGUI/src/CEGUILoadingTaskManager.cpp \
	../CEGUI/src/ETCHeader.cpp \
	../CEGUI/src/elements/CEGUIAnimateText.cpp \
	../CEGUI/src/elements/CEGUIAnimationButton.cpp \
	../CEGUI/src/elements/CEGUIAnimationButtonProperties.cpp \
	../CEGUI/src/elements/CEGUIButtonBase.cpp \
	../CEGUI/src/elements/CEGUICheckbox.cpp \
	../CEGUI/src/elements/CEGUICheckboxProperties.cpp \
	../CEGUI/src/elements/CEGUIClippedContainer.cpp \
	../CEGUI/src/elements/CEGUIComboDropList.cpp \
	../CEGUI/src/elements/CEGUICombobox.cpp \
	../CEGUI/src/elements/CEGUIComboboxProperties.cpp \
	../CEGUI/src/elements/CEGUICompnentTip.cpp \
	../CEGUI/src/elements/CEGUIDragContainer.cpp \
	../CEGUI/src/elements/CEGUIDragContainerProperties.cpp \
	../CEGUI/src/elements/CEGUIEditbox.cpp \
	../CEGUI/src/elements/CEGUIEditboxProperties.cpp \
	../CEGUI/src/elements/CEGUIFrameWindow.cpp \
	../CEGUI/src/elements/CEGUIFrameWindowProperties.cpp \
	../CEGUI/src/elements/CEGUIGUISheet.cpp \
	../CEGUI/src/elements/CEGUIGroupBox.cpp \
	../CEGUI/src/elements/CEGUIGroupBtnItem.cpp \
	../CEGUI/src/elements/CEGUIGroupBtnTree.cpp \
	../CEGUI/src/elements/CEGUIGroupButton.cpp \
	../CEGUI/src/elements/CEGUIGroupButtonProperties.cpp \
	../CEGUI/src/elements/CEGUIIrregularButton.cpp \
	../CEGUI/src/elements/CEGUIIrregularButtonProperties.cpp \
	../CEGUI/src/elements/CEGUIIrregularFigure.cpp \
	../CEGUI/src/elements/CEGUIItemCell.cpp \
	../CEGUI/src/elements/CEGUIItemCellGeneral.cpp \
	../CEGUI/src/elements/CEGUIItemCellProperties.cpp \
	../CEGUI/src/elements/CEGUIItemEntry.cpp \
	../CEGUI/src/elements/CEGUIItemEntryProperties.cpp \
	../CEGUI/src/elements/CEGUIItemListBase.cpp \
	../CEGUI/src/elements/CEGUIItemListBaseProperties.cpp \
	../CEGUI/src/elements/CEGUIItemListbox.cpp \
	../CEGUI/src/elements/CEGUIItemListboxProperties.cpp \
	../CEGUI/src/elements/CEGUIItemTable.cpp \
	../CEGUI/src/elements/CEGUIItemTableProperties.cpp \
	../CEGUI/src/elements/CEGUILinkText.cpp \
	../CEGUI/src/elements/CEGUILinkTextProperties.cpp \
	../CEGUI/src/elements/CEGUIListHeader.cpp \
	../CEGUI/src/elements/CEGUIListHeaderProperties.cpp \
	../CEGUI/src/elements/CEGUIListHeaderSegment.cpp \
	../CEGUI/src/elements/CEGUIListHeaderSegmentProperties.cpp \
	../CEGUI/src/elements/CEGUIListbox.cpp \
	../CEGUI/src/elements/CEGUIListboxItem.cpp \
	../CEGUI/src/elements/CEGUIListboxProperties.cpp \
	../CEGUI/src/elements/CEGUIListboxTextItem.cpp \
	../CEGUI/src/elements/CEGUIMenuBase.cpp \
	../CEGUI/src/elements/CEGUIMenuBaseProperties.cpp \
	../CEGUI/src/elements/CEGUIMenuItem.cpp \
	../CEGUI/src/elements/CEGUIMenubar.cpp \
	../CEGUI/src/elements/CEGUIMessageTip.cpp \
	../CEGUI/src/elements/CEGUIMultiColumnList.cpp \
	../CEGUI/src/elements/CEGUIMultiColumnListProperties.cpp \
	../CEGUI/src/elements/CEGUIMultiLineEditbox.cpp \
	../CEGUI/src/elements/CEGUIMultiLineEditboxProperties.cpp \
	../CEGUI/src/elements/CEGUIPanelChengJiuItem.cpp \
	../CEGUI/src/elements/CEGUIPanelChengWeiItem.cpp \
	../CEGUI/src/elements/CEGUIPanelItem.cpp \
	../CEGUI/src/elements/CEGUIPanelQiYuanItem.cpp \
	../CEGUI/src/elements/CEGUIPanelbox.cpp \
	../CEGUI/src/elements/CEGUIPopupMenu.cpp \
	../CEGUI/src/elements/CEGUIPopupMenuProperties.cpp \
	../CEGUI/src/elements/CEGUIProgressBar.cpp \
	../CEGUI/src/elements/CEGUIProgressBarProperties.cpp \
	../CEGUI/src/elements/CEGUIProgressBarTwoValue.cpp \
	../CEGUI/src/elements/CEGUIProgressBarTwoValueProperties.cpp \
	../CEGUI/src/elements/CEGUIPushButton.cpp \
	../CEGUI/src/elements/CEGUIPushButtonProperties.cpp \
	../CEGUI/src/elements/CEGUIRadioButton.cpp \
	../CEGUI/src/elements/CEGUIRadioButtonProperties.cpp \
	../CEGUI/src/elements/CEGUIRichEditbox.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxAnswerQuestionLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxButtonImageComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxEmotionComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxFamilyRecruitLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxGoToComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxHttpComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxImageComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxJoinTeamLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxRequestTeamLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxCommonLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxRequestOtherQuestComponent.cpp \
	../CEGUI/src/elements/RichEditboxOpenDialogComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxLineBreakComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxLinkTextComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxNameLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxProperties.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxTextComponent.cpp \
	../CEGUI/src/elements/CEGUIRichEditboxTipsLinkComponent.cpp \
	../CEGUI/src/elements/CEGUIScrollablePane.cpp \
	../CEGUI/src/elements/CEGUIScrollablePaneProperties.cpp \
	../CEGUI/src/elements/CEGUIScrollbar.cpp \
	../CEGUI/src/elements/CEGUIScrollbarProperties.cpp \
	../CEGUI/src/elements/CEGUIScrolledContainer.cpp \
	../CEGUI/src/elements/CEGUIScrolledContainerProperties.cpp \
	../CEGUI/src/elements/CEGUIScrolledItemListBase.cpp \
	../CEGUI/src/elements/CEGUIScrolledItemListBaseProperties.cpp \
	../CEGUI/src/elements/CEGUISkillBox.cpp \
	../CEGUI/src/elements/CEGUISlider.cpp \
	../CEGUI/src/elements/CEGUISliderProperties.cpp \
	../CEGUI/src/elements/CEGUISpecialTree.cpp \
	../CEGUI/src/elements/CEGUISpecialTreeItem.cpp \
	../CEGUI/src/elements/CEGUISpinner.cpp \
	../CEGUI/src/elements/CEGUISpinnerProperties.cpp \
	../CEGUI/src/elements/CEGUISwitch.cpp \
	../CEGUI/src/elements/CEGUISwitchProperties.cpp \
	../CEGUI/src/elements/CEGUITabButton.cpp \
	../CEGUI/src/elements/CEGUITabControl.cpp \
	../CEGUI/src/elements/CEGUITabControlProperties.cpp \
	../CEGUI/src/elements/CEGUIThumb.cpp \
	../CEGUI/src/elements/CEGUIThumbProperties.cpp \
	../CEGUI/src/elements/CEGUITitlebar.cpp \
	../CEGUI/src/elements/CEGUITitlebarProperties.cpp \
	../CEGUI/src/elements/CEGUITooltip.cpp \
	../CEGUI/src/elements/CEGUITooltipProperties.cpp \
	../CEGUI/src/elements/CEGUITree.cpp \
	../CEGUI/src/elements/CEGUITreeItem.cpp \
	../CEGUI/src/elements/CEGUITreeProperties.cpp \
	../CEGUI/src/falagard/CEGUIFalComponentBase.cpp \
	../CEGUI/src/falagard/CEGUIFalDimensions.cpp \
	../CEGUI/src/falagard/CEGUIFalFrameComponent.cpp \
	../CEGUI/src/falagard/CEGUIFalImageryComponent.cpp \
	../CEGUI/src/falagard/CEGUIFalImagerySection.cpp \
	../CEGUI/src/falagard/CEGUIFalLayerSpecification.cpp \
	../CEGUI/src/falagard/CEGUIFalNamedArea.cpp \
	../CEGUI/src/falagard/CEGUIFalPropertyDefinition.cpp \
	../CEGUI/src/falagard/CEGUIFalPropertyDefinitionBase.cpp \
	../CEGUI/src/falagard/CEGUIFalPropertyInitialiser.cpp \
	../CEGUI/src/falagard/CEGUIFalPropertyLinkDefinition.cpp \
	../CEGUI/src/falagard/CEGUIFalSectionSpecification.cpp \
	../CEGUI/src/falagard/CEGUIFalStateImagery.cpp \
	../CEGUI/src/falagard/CEGUIFalTextComponent.cpp \
	../CEGUI/src/falagard/CEGUIFalWidgetComponent.cpp \
	../CEGUI/src/falagard/CEGUIFalWidgetLookFeel.cpp \
	../CEGUI/src/falagard/CEGUIFalWidgetLookManager.cpp \
	../CEGUI/src/falagard/CEGUIFalXMLEnumHelper.cpp \
	../CEGUI/src/falagard/CEGUIFalagard_xmlHandler.cpp \
	../CEGUI/src/gesture/CEGUIGestureRecognizer.cpp \
	../CEGUI/src/gesture/CEGUIGestureRecognizerManager.cpp \
	../CEGUI/src/gesture/CEGUILongPressGestureRecognizer.cpp \
	../CEGUI/src/gesture/CEGUIPanGestureRecognizer.cpp \
	../CEGUI/src/BinLayout/CEGUIBinLayoutFileSerializer.cpp \
	../CEGUI/src/BinLayout/CEGUIFileStream.cpp \
	../CEGUI/src/BinLayout/CEGUIMemoryStream.cpp \
	../CEGUI/src/BinLayout/CEGUIPropertyIds.cpp \
	../CEGUI/src/BinLayout/CEGUIPropertySerializer.cpp \
	../CEGUI/src/BinLayout/CEGUISerializerManager.cpp \
	../CEGUI/src/BinLayout/CEGUIStream.cpp \
	../CEGUI/src/BinLayout/CEGUIXMLFileData.cpp \
	../CEGUI/src/BinLayout/CEGUIXMLToBin.cpp \
	../CEGUI/src/BinLayout/v1/CEGUILayoutSerializer_v1.cpp \
	../CEGUI/src/BinLayout/v1/CEGUINodeSerializer_v1.cpp \
	../CEGUI/src/BinLayout/v1/CEGUIPropertySerializer_v1.cpp \
	../CEGUI/src/BinLayout/v1/CEGUIRegSerializers_v1.cpp \


LOCAL_C_INCLUDES := $(LOCAL_PATH)/../CEGUI/include \
	$(LOCAL_PATH)/../../freetype-2.4.9/include \
	$(LOCAL_PATH)/../../pcre-8.31/prj2 \
	$(LOCAL_PATH)/../../../cocos2d-2.0-rc2-x-2.0.1/cocos2dx \
	$(LOCAL_PATH)/../../../cocos2d-2.0-rc2-x-2.0.1/cocos2dx/include \
	$(LOCAL_PATH)/../../../cocos2d-2.0-rc2-x-2.0.1/cocos2dx/platform \
	$(LOCAL_PATH)/../../../cocos2d-2.0-rc2-x-2.0.1/cocos2dx/platform/android \
	$(LOCAL_PATH)/../../../cocos2d-2.0-rc2-x-2.0.1/cocos2dx/kazmath/include \
	$(LOCAL_PATH)/../../../common \
	$(LOCAL_PATH)/../../../common/platform \
	$(LOCAL_PATH)/../CEGUI/include/RendererModules/Cocos2D \


LOCAL_LDLIBS := -llog \

LOCAL_CFLAGS := -DPUBLISHED_VERSION \
	-DUSE_FILE32API \
	-D_OS_IOS \
	-D_OS_ANDROID \
	-DHAVE_CONFIG_H \
	-DCEGUI_STATIC \
	-DFireEventCrash \
	-DANDROID \
	-DCC_SUPPORT_PVRTC \


LOCAL_CPPFLAGS := -fexceptions -fpermissive

include $(BUILD_STATIC_LIBRARY)


